<?php

namespace CRM\Tests\Integration;

use CRM\CacheManager;
use CRM\Database;
use CRM\Modules\DealAutomationConfig;
use CRM\Modules\CompanyProfile;
use CRM\Modules\InvoiceSettings;
use CRM\Modules\UserPreferences;
use CRM\Services\EmailIntegrationService;
use CRM\Services\WorkspaceContext;
use CRM\Services\WorkspaceOnboardingService;
use CRM\Services\WorkspacePlanEntitlementService;
use CRM\Services\WorkspaceProvisioningService;
use CRM\Services\WorkspaceSkillCatalogService;
use CRM\Tests\DatabaseTestCase;
use CRM\Tests\Support\EndpointHarness;

class DashboardSetupPopupTest extends DatabaseTestCase
{
    use EndpointHarness;

    public function testDashboardRendersSetupPopupBelowOperationalThreshold(): void
    {
        $seed = $this->seedQuickStartWorkspace('popup-visible', true);

        $response = $this->runWebEndpoint('public/dashboard.php', $this->webSession($seed), [
            'method' => 'GET',
        ]);
        $body = (string) ($response['body'] ?? '');

        $this->assertSame(200, (int) ($response['status'] ?? 0), (string) ($response['stderr'] ?? ''));
        $this->assertStringContainsString('id="dashboard-setup-popup"', $body);
        $this->assertStringContainsString('dashboard/dismiss-setup-popup.php', $body);
        $this->assertStringNotContainsString('Generate my operating brief', $body);
        $this->assertStringContainsString('class="container workspace-setup-impact"', $body);
        $this->assertStringNotContainsString('workspace-setup-complete-title">Ready for daily work', $body);
        $this->assertDashboardAutoGeneratedOperatingBrief((int) $seed['workspace_id']);
    }

    public function testDashboardShowsWelcomeOverlayAndProductDemoPromptAfterOnboardingCompletion(): void
    {
        $seed = $this->seedQuickStartWorkspace('popup-welcome-demo', true);

        $response = $this->runWebEndpoint('public/dashboard.php', $this->webSession($seed), [
            'method' => 'GET',
            'query' => ['onboarding' => 'complete'],
        ]);
        $body = (string) ($response['body'] ?? '');

        $this->assertSame(200, (int) ($response['status'] ?? 0), (string) ($response['stderr'] ?? ''));
        $this->assertStringContainsString('Welcome to Clarity', $body);
        $this->assertStringContainsString('id="dashboard-product-demo-prompt"', $body);
        $this->assertStringContainsString('View product demo', $body);
        $this->assertStringContainsString('name="action" value="start_demo"', $body);
        $this->assertStringNotContainsString('Explore a normal CRM workday', $body);
        $this->assertStringNotContainsString('You are on Compass Free', $body);
    }

    public function testDashboardDoesNotRenderSetupPopupAfterDismissal(): void
    {
        $seed = $this->seedQuickStartWorkspace('popup-dismissed', true);
        (new UserPreferences())->setPreference((int) $seed['user_id'], 'dashboard_setup_popup_dismissed', '1');

        $response = $this->runWebEndpoint('public/dashboard.php', $this->webSession($seed), [
            'method' => 'GET',
        ]);
        $body = (string) ($response['body'] ?? '');

        $this->assertSame(200, (int) ($response['status'] ?? 0), (string) ($response['stderr'] ?? ''));
        $this->assertStringNotContainsString('id="dashboard-setup-popup"', $body);
        $this->assertStringNotContainsString('Generate my operating brief', $body);
        $this->assertStringContainsString('class="container workspace-setup-impact"', $body);
        $this->assertStringNotContainsString('workspace-setup-complete-title">Ready for daily work', $body);
        $this->assertDashboardAutoGeneratedOperatingBrief((int) $seed['workspace_id']);
    }

    public function testDashboardRendersFullSetupCardBelowOneHundredPercent(): void
    {
        $seed = $this->seedMostlyOperationalWorkspace('popup-threshold');

        $impact = (new WorkspaceOnboardingService())->getDashboardSetupImpact((int) $seed['workspace_id'], (int) $seed['user_id']);
        $this->assertGreaterThanOrEqual(80, (int) ($impact['score'] ?? 0));
        $this->assertLessThan(100, (int) ($impact['score'] ?? 0));

        $response = $this->runWebEndpoint('public/dashboard.php', $this->webSession($seed), [
            'method' => 'GET',
        ]);
        $body = (string) ($response['body'] ?? '');

        $this->assertSame(200, (int) ($response['status'] ?? 0), (string) ($response['stderr'] ?? ''));
        $this->assertStringNotContainsString('id="dashboard-setup-popup"', $body);
        $this->assertStringNotContainsString('Generate my operating brief', $body);
        $this->assertStringContainsString('class="container workspace-setup-impact"', $body);
        $this->assertStringNotContainsString('workspace-setup-complete-title">Ready for daily work', $body);
        $this->assertDashboardAutoGeneratedOperatingBrief((int) $seed['workspace_id']);
    }

    public function testDashboardTreatsOneSeatPackageAsCompleteWithoutTeamInvite(): void
    {
        $seed = $this->seedOneSeatOperationalWorkspace('popup-one-seat-complete');

        $impact = (new WorkspaceOnboardingService())->getDashboardSetupImpact((int) $seed['workspace_id'], (int) $seed['user_id']);
        $actionKeys = array_column((array) ($impact['actions'] ?? []), 'key');
        $this->assertSame(100, (int) ($impact['score'] ?? 0));
        $this->assertNotContains('invite_team', $actionKeys);
        $this->assertContains('team', (array) ($impact['completed_actions'] ?? []));

        $response = $this->runWebEndpoint('public/dashboard.php', $this->webSession($seed), [
            'method' => 'GET',
        ]);
        $body = (string) ($response['body'] ?? '');

        $this->assertSame(200, (int) ($response['status'] ?? 0), (string) ($response['stderr'] ?? ''));
        $this->assertStringNotContainsString('id="dashboard-setup-popup"', $body);
        $this->assertStringNotContainsString('class="container workspace-setup-impact"', $body);
        $this->assertStringContainsString('workspace-setup-complete-title">Ready for daily work', $body);
    }

    public function testDashboardShowsCompactCompleteBannerAtOneHundredPercent(): void
    {
        $seed = $this->seedFullyOperationalWorkspace('popup-complete');

        $response = $this->runWebEndpoint('public/dashboard.php', $this->webSession($seed), [
            'method' => 'GET',
        ]);
        $body = (string) ($response['body'] ?? '');

        $this->assertSame(200, (int) ($response['status'] ?? 0), (string) ($response['stderr'] ?? ''));
        $this->assertStringNotContainsString('id="dashboard-setup-popup"', $body);
        $this->assertStringNotContainsString('class="container workspace-setup-impact"', $body);
        $this->assertStringContainsString('class="container workspace-setup-complete-banner"', $body);
        $this->assertStringContainsString('workspace-setup-complete-title">Ready for daily work', $body);
        $this->assertStringContainsString('Core setup is complete. Dashboard focus has shifted to revenue, tasks, pipeline, and guided next actions.', $body);
        $this->assertStringContainsString('dismiss_type=setup_complete', $body);
    }

    public function testDashboardHidesCompleteBannerAfterDismissal(): void
    {
        $seed = $this->seedFullyOperationalWorkspace('popup-complete-dismissed');
        (new UserPreferences())->setPreference(
            (int) $seed['user_id'],
            'dashboard_setup_complete_dismissed:' . (int) $seed['workspace_id'],
            '1'
        );

        $response = $this->runWebEndpoint('public/dashboard.php', $this->webSession($seed), [
            'method' => 'GET',
        ]);
        $body = (string) ($response['body'] ?? '');

        $this->assertSame(200, (int) ($response['status'] ?? 0), (string) ($response['stderr'] ?? ''));
        $this->assertStringNotContainsString('class="container workspace-setup-impact"', $body);
        $this->assertStringNotContainsString('class="container workspace-setup-complete-banner"', $body);
        $this->assertStringNotContainsString('workspace-setup-complete-title">Ready for daily work', $body);
    }

    public function testDashboardShowsFullSetupCardBelowOneHundredAfterCompleteDismissal(): void
    {
        $seed = $this->seedMostlyOperationalWorkspace('popup-complete-later-incomplete');
        (new UserPreferences())->setPreference(
            (int) $seed['user_id'],
            'dashboard_setup_complete_dismissed:' . (int) $seed['workspace_id'],
            '1'
        );

        $impact = (new WorkspaceOnboardingService())->getDashboardSetupImpact((int) $seed['workspace_id'], (int) $seed['user_id']);
        $this->assertLessThan(100, (int) ($impact['score'] ?? 0));

        $response = $this->runWebEndpoint('public/dashboard.php', $this->webSession($seed), [
            'method' => 'GET',
        ]);
        $body = (string) ($response['body'] ?? '');

        $this->assertSame(200, (int) ($response['status'] ?? 0), (string) ($response['stderr'] ?? ''));
        $this->assertStringContainsString('class="container workspace-setup-impact"', $body);
        $this->assertStringNotContainsString('class="container workspace-setup-complete-banner"', $body);
        $this->assertStringNotContainsString('workspace-setup-complete-title">Ready for daily work', $body);
    }

    public function testDashboardShowsAiCoachButtonWithoutBlockingBriefGateBeforeClarityJourneyContext(): void
    {
        $seed = $this->provisionWorkspace('popup-coach-brief');
        $workspaceId = (int) $seed['workspace_id'];
        $userId = (int) $seed['user_id'];
        $catalog = new WorkspaceSkillCatalogService();
        $this->syncWorkspaceSkillDefinitionsForTest();
        $catalog->saveCatalogOverride(WorkspaceSkillCatalogService::SKILL_AI_COACH, [
            'explainer_video_url' => 'https://youtu.be/dQw4w9WgXcQ',
            'explainer_orientation' => 'landscape',
        ], $userId);
        $this->installAiCoachForDashboard($seed);

        $onboarding = new WorkspaceOnboardingService();
        $onboarding->saveStep($workspaceId, $userId, 1, [
            'company_name' => 'Coach Gate Co',
            'company_industry' => 'Professional services',
            'company_description' => 'A shared workspace context exists before optional strategy refinements.',
            'success_outcome' => 'Every user gets better AI Coach guidance.',
        ]);
        $onboarding->saveStep($workspaceId, $userId, 2, [
            'product_name' => 'Coach Gate Offer',
            'product_description' => 'A practical service offer.',
            'target_audience' => 'Founder-led teams',
            'pricing_info' => 'Starts at 500 USD',
        ]);
        Database::execute(
            "UPDATE workspace_onboarding_state
             SET status = 'completed',
                 completed_at = COALESCE(completed_at, NOW())
             WHERE workspace_id = ?",
            [$workspaceId]
        );

        $response = $this->runWebEndpoint('public/dashboard.php', $this->webSession($seed), [
            'method' => 'GET',
        ]);
        $body = (string) ($response['body'] ?? '');

        $this->assertSame(200, (int) ($response['status'] ?? 0), (string) ($response['stderr'] ?? ''));
        $this->assertStringContainsString('id="ai-coach-open"', $body);
        $this->assertStringContainsString('aria-label="Open AI Coach daily brief"', $body);
        $this->assertStringContainsString('css/ai-coach.css', $body);
        $this->assertStringContainsString('data-ai-coach-access-pending hidden aria-hidden="true"', $body);
        $this->assertStringNotContainsString('id="ai-coach-brief-gate"', $body);
        $this->assertStringNotContainsString('Complete your Personal Coach Brief', $body);
        $this->assertStringNotContainsString('requires your Personal Coach Brief', $body);
        $this->assertStringNotContainsString('data-ai-coach-brief-snooze', $body);
        $this->assertStringNotContainsString('data-ai-coach-brief-dismiss', $body);
        $this->assertStringNotContainsString('Remind me later', $body);
        $this->assertAiCoachAccess($seed, true, true);
    }

    public function testDashboardHidesAiCoachButtonWhenAiCoachIsNotInstalled(): void
    {
        $seed = $this->seedQuickStartWorkspace('popup-coach-not-installed');
        $this->syncWorkspaceSkillDefinitionsForTest();
        Database::execute(
            "DELETE FROM workspace_skill_installs
             WHERE workspace_id = ?
               AND skill_key = ?",
            [
                (int) $seed['workspace_id'],
                WorkspaceSkillCatalogService::SKILL_AI_COACH,
            ]
        );

        $response = $this->runWebEndpoint('public/dashboard.php', $this->webSession($seed), [
            'method' => 'GET',
        ]);
        $body = (string) ($response['body'] ?? '');

        $this->assertSame(200, (int) ($response['status'] ?? 0), (string) ($response['stderr'] ?? ''));
        $this->assertStringNotContainsString('id="ai-coach-open"', $body);
        $this->assertStringNotContainsString('<section class="hero-actions-row ai-coach-launcher"', $body);
        $this->assertStringNotContainsString('css/ai-coach.css', $body);
        $this->assertStringContainsString('aiCoachScriptUrl: null', $body);
        $this->assertStringContainsString('aiCoachAccessUrl: null', $body);
        $this->assertStringNotContainsString('id="ai-coach-brief-gate"', $body);
        $this->assertAiCoachAccess($seed, false, false);
    }

    public function testDashboardHidesAiCoachButtonWhenAiCoachIsDisabled(): void
    {
        $seed = $this->seedQuickStartWorkspace('popup-coach-disabled');
        $this->syncWorkspaceSkillDefinitionsForTest();
        $this->installAiCoachForDashboard($seed, [
            'ai_coach_enabled' => false,
            'ai_coach' => [
                'enabled' => false,
            ],
        ]);

        $response = $this->runWebEndpoint('public/dashboard.php', $this->webSession($seed), [
            'method' => 'GET',
        ]);
        $body = (string) ($response['body'] ?? '');

        $this->assertSame(200, (int) ($response['status'] ?? 0), (string) ($response['stderr'] ?? ''));
        $this->assertStringContainsString('id="ai-coach-open"', $body);
        $this->assertStringContainsString('data-ai-coach-access-pending hidden aria-hidden="true"', $body);
        $this->assertStringNotContainsString('id="ai-coach-brief-gate"', $body);
        $this->assertAiCoachAccess($seed, false, true);
    }

    public function testDashboardHidesAiCoachButtonWhenRuntimeAccessIsDenied(): void
    {
        $seed = $this->seedQuickStartWorkspace('popup-coach-runtime-denied');
        $this->syncWorkspaceSkillDefinitionsForTest();
        $this->installAiCoachForDashboard($seed);

        $catalog = new WorkspaceSkillCatalogService();
        $catalog->setCatalogStatus(
            WorkspaceSkillCatalogService::SKILL_AI_COACH,
            WorkspaceSkillCatalogService::CATALOG_STATUS_DEACTIVATED,
            (int) $seed['user_id']
        );

        try {
            $response = $this->runWebEndpoint('public/dashboard.php', $this->webSession($seed), [
                'method' => 'GET',
            ]);
            $body = (string) ($response['body'] ?? '');

            $this->assertSame(200, (int) ($response['status'] ?? 0), (string) ($response['stderr'] ?? ''));
            $this->assertStringNotContainsString('id="ai-coach-open"', $body);
            $this->assertStringNotContainsString('<section class="hero-actions-row ai-coach-launcher"', $body);
            $this->assertStringNotContainsString('css/ai-coach.css', $body);
            $this->assertStringNotContainsString('id="ai-coach-brief-gate"', $body);
            $this->assertAiCoachAccess($seed, false, false);
        } finally {
            $catalog->resetCatalogOverride(WorkspaceSkillCatalogService::SKILL_AI_COACH);
        }
    }

    public function testDismissSetupPopupRequiresAuthentication(): void
    {
        $response = $this->runEndpointScript('api/dashboard/dismiss-setup-popup.php', [
            'method' => 'POST',
            'post' => ['csrf_token' => 'csrf-dashboard-popup'],
        ]);

        $this->assertSame(401, (int) ($response['status'] ?? 0));
    }

    public function testDismissSetupPopupRejectsInvalidCsrf(): void
    {
        $seed = $this->seedQuickStartWorkspace('popup-bad-csrf');

        $response = $this->runWebEndpoint('api/dashboard/dismiss-setup-popup.php', $this->webSession($seed), [
            'method' => 'POST',
            'post' => ['csrf_token' => 'bad', 'dismiss_type' => 'setup_complete'],
        ]);

        $this->assertSame(403, (int) ($response['status'] ?? 0));
    }

    public function testDismissSetupPopupStoresPreference(): void
    {
        $seed = $this->seedQuickStartWorkspace('popup-store');

        $response = $this->runWebEndpoint('api/dashboard/dismiss-setup-popup.php', $this->webSession($seed), [
            'method' => 'POST',
            'post' => ['csrf_token' => 'csrf-dashboard-popup'],
        ]);

        $this->assertSame(200, (int) ($response['status'] ?? 0), (string) ($response['stderr'] ?? ''));
        $this->assertSame(
            '1',
            (new UserPreferences())->getPreference((int) $seed['user_id'], 'dashboard_setup_popup_dismissed')
        );
    }

    public function testDismissSetupCompleteStoresWorkspaceScopedPreference(): void
    {
        $seed = $this->seedFullyOperationalWorkspace('popup-complete-store');

        $response = $this->runWebEndpoint('api/dashboard/dismiss-setup-popup.php', $this->webSession($seed), [
            'method' => 'POST',
            'post' => [
                'csrf_token' => 'csrf-dashboard-popup',
                'dismiss_type' => 'setup_complete',
            ],
        ]);

        $this->assertSame(200, (int) ($response['status'] ?? 0), (string) ($response['stderr'] ?? ''));
        $preferences = new UserPreferences();
        $this->assertSame(
            '1',
            $preferences->getPreference(
                (int) $seed['user_id'],
                'dashboard_setup_complete_dismissed:' . (int) $seed['workspace_id']
            )
        );
        $this->assertNull($preferences->getPreference((int) $seed['user_id'], 'dashboard_setup_popup_dismissed'));
    }

    /**
     * @return array{workspace_id:int,user_id:int,workspace_uuid:string,workspace_slug:string,workspace_name:string,membership_id:int}
     */
    private function seedQuickStartWorkspace(string $slugPrefix, bool $multiSeatPackage = false): array
    {
        $seed = $this->provisionWorkspace($slugPrefix);
        (new DealAutomationConfig())->save([
            'enabled' => false,
            'mode' => 'suggest_only',
        ]);
        (new WorkspaceOnboardingService())->completeQuickStart((int) $seed['workspace_id'], (int) $seed['user_id'], [
            'company_name' => 'Popup Co',
            'company_industry' => 'Home services',
            'company_description' => 'Popup Co helps homeowners book reliable service visits.',
            'communication_channel' => 'whatsapp',
            'product_name' => 'Service visit',
            'product_description' => 'A fast booking and service coordination offer.',
            'ideal_customer_profile' => 'Busy homeowners who need trusted service providers.',
            'relationship_style' => 'friendly_operator',
            'draft_tone_preset' => 'warm',
            'escalation_preference' => 'Complaints and urgent scheduling issues',
        ]);
        if ($multiSeatPackage) {
            $this->setWorkspacePlan($seed, 'founder-plus-monthly');
        }
        $this->clearDashboardSetupImpactCache((int) $seed['workspace_id'], (int) $seed['user_id']);

        return $seed;
    }

    /**
     * @return array{workspace_id:int,user_id:int,workspace_uuid:string,workspace_slug:string,workspace_name:string,membership_id:int}
     */
    private function seedFullyOperationalWorkspace(string $slugPrefix): array
    {
        $seed = $this->seedMostlyOperationalWorkspace($slugPrefix);
        $this->addActiveWorkspaceMember($seed);
        $this->clearDashboardSetupImpactCache((int) $seed['workspace_id'], (int) $seed['user_id']);

        $impact = (new WorkspaceOnboardingService())->getDashboardSetupImpact((int) $seed['workspace_id'], (int) $seed['user_id']);
        $this->assertSame(100, (int) ($impact['score'] ?? 0));

        return $seed;
    }

    private function assertDashboardAutoGeneratedOperatingBrief(int $workspaceId): void
    {
        $row = Database::queryOne(
            "SELECT launch_summary_json FROM workspace_onboarding_state WHERE workspace_id = ? LIMIT 1",
            [$workspaceId]
        ) ?: [];
        $summary = json_decode((string) ($row['launch_summary_json'] ?? ''), true);

        $this->assertIsArray($summary);
        $this->assertArrayHasKey('operating_brief', $summary);
        $this->assertStringContainsString(
            'Workspace Operating Brief',
            (string) ($summary['operating_brief']['markdown'] ?? '')
        );
    }

    /**
     * @param array{workspace_id:int,user_id:int} $seed
     */
    private function assertAiCoachAccess(array $seed, bool $expectedEnabled, bool $expectedInstalled): void
    {
        $response = $this->runWebEndpoint('api/dashboard/ai_coach_access.php', $this->webSession($seed), [
            'method' => 'GET',
        ]);
        $payload = json_decode((string) ($response['body'] ?? ''), true);

        $this->assertSame(200, (int) ($response['status'] ?? 0), (string) ($response['stderr'] ?? ''));
        $this->assertIsArray($payload);
        $this->assertSame($expectedInstalled, (bool) ($payload['installed'] ?? false));
        $this->assertSame($expectedEnabled, (bool) ($payload['enabled'] ?? false));
    }

    /**
     * @return array{workspace_id:int,user_id:int,workspace_uuid:string,workspace_slug:string,workspace_name:string,membership_id:int}
     */
    private function seedMostlyOperationalWorkspace(string $slugPrefix): array
    {
        $seed = $this->seedOneSeatOperationalWorkspace($slugPrefix);
        $this->setWorkspacePlan($seed, 'founder-plus-monthly');
        $this->clearDashboardSetupImpactCache((int) $seed['workspace_id'], (int) $seed['user_id']);

        return $seed;
    }

    /**
     * @return array{workspace_id:int,user_id:int,workspace_uuid:string,workspace_slug:string,workspace_name:string,membership_id:int}
     */
    private function seedOneSeatOperationalWorkspace(string $slugPrefix): array
    {
        $seed = $this->provisionWorkspace($slugPrefix);

        $service = new WorkspaceOnboardingService();
        $service->saveStep((int) $seed['workspace_id'], (int) $seed['user_id'], 1, [
            'company_name' => 'Operational Co',
            'company_industry' => 'Professional services',
            'company_description' => 'Operational Co helps service teams follow up faster.',
            'success_outcome' => 'Fewer missed leads and clearer next actions.',
        ]);
        $service->saveStep((int) $seed['workspace_id'], (int) $seed['user_id'], 2, [
            'communication_channel' => 'email',
            'product_name' => 'Outcome Engine',
            'product_description' => 'A practical CRM implementation service.',
            'pricing_info' => 'Starts at 500 USD',
            'ideal_customer_profile' => 'Growing service teams with inconsistent follow-up.',
            'offer_angle' => 'Make every lead easier to move.',
        ]);
        $service->saveStep((int) $seed['workspace_id'], (int) $seed['user_id'], 3, [
            'relationship_style' => 'trusted_advisor',
            'draft_tone_preset' => 'warm',
            'draft_cta_style' => 'clear',
            'draft_formality_level' => 'balanced',
            'draft_reading_level' => 'professional',
            'words_to_avoid' => 'unapproved discounts',
            'escalation_preference' => 'Refunds and complaints',
        ]);
        $service->saveStep((int) $seed['workspace_id'], (int) $seed['user_id'], 4, [
            'technical_level' => 'work_with_me',
            'ai_best_practices_enabled' => '1',
            'deal_automation_enabled' => '1',
        ]);
        $service->saveStep((int) $seed['workspace_id'], (int) $seed['user_id'], 5, [
            'clarity_context_submitted' => '',
        ]);
        (new CompanyProfile())->update([
            'company_legal_name' => 'Operational Co Ltd',
        ]);

        (new InvoiceSettings())->save([
            'enabled' => true,
            'default_currency' => 'KES',
            'default_payment_terms_days' => 14,
            'bank_instructions' => 'Pay by bank transfer.',
        ], (int) $seed['user_id']);
        (new EmailIntegrationService())->storeManualMailIntegration((int) $seed['user_id'], [
            'smtp_host' => 'smtp.example.test',
            'smtp_username' => 'owner@example.test',
            'smtp_password' => 'smtp-secret',
            'from_email' => 'owner@example.test',
            'from_name' => 'Operational Co',
        ], (int) $seed['workspace_id']);
        (new DealAutomationConfig())->save([
            'enabled' => true,
            'mode' => 'auto_safe',
        ]);
        $this->clearDashboardSetupImpactCache((int) $seed['workspace_id'], (int) $seed['user_id']);

        return $seed;
    }

    /**
     * @param array{workspace_id:int,user_id:int,workspace_uuid:string,workspace_slug:string,workspace_name:string,membership_id:int} $seed
     */
    private function addActiveWorkspaceMember(array $seed): void
    {
        $suffix = strtolower(bin2hex(random_bytes(4)));
        Database::execute(
            "INSERT INTO users (uuid, email, password_hash, role, created_at)
             VALUES (UUID(), ?, ?, 'sales', NOW())",
            [
                'dashboard.popup.teammate.' . $suffix . '@example.test',
                password_hash('P@ssword123!', PASSWORD_DEFAULT),
            ]
        );
        $teammateId = (int) Database::lastInsertId();
        Database::execute(
            "INSERT INTO workspace_memberships (workspace_id, user_id, role_slug, membership_status, is_owner, joined_at, invited_by)
             VALUES (?, ?, 'member', 'active', 0, NOW(), ?)",
            [
                (int) $seed['workspace_id'],
                $teammateId,
                (int) $seed['user_id'],
            ]
        );
    }

    private function clearDashboardSetupImpactCache(int $workspaceId, int $userId): void
    {
        $cache = new CacheManager();
        $cache->delete('dashboard_setup_impact:v2:' . $workspaceId . ':' . $userId);
        $cache->delete('dashboard_setup_impact:v3:' . $workspaceId . ':' . $userId);
        $cache->delete('dashboard_setup_cards:v1:' . $workspaceId);
    }

    /**
     * @param array{workspace_id:int,user_id:int,workspace_uuid:string,workspace_slug:string,workspace_name:string,membership_id:int} $seed
     */
    private function setWorkspacePlan(array $seed, string $priceCode): void
    {
        $price = (new WorkspacePlanEntitlementService())->priceByCode($priceCode);
        $this->assertIsArray($price);
        $this->assertGreaterThan(0, (int) ($price['id'] ?? 0));

        Database::execute(
            "UPDATE workspace_subscriptions
             SET billing_plan_price_id = ?,
                 subscription_status = 'active'
             WHERE workspace_id = ?",
            [(int) $price['id'], (int) $seed['workspace_id']]
        );
    }

    private function syncWorkspaceSkillDefinitionsForTest(): void
    {
        $reflection = new \ReflectionClass(WorkspaceSkillCatalogService::class);
        $definitionsSynced = $reflection->getProperty('definitionsSynced');
        $definitionsSynced->setAccessible(true);
        $definitionsSynced->setValue(false);
        $contractColumnsReady = $reflection->getProperty('contractColumnsReady');
        $contractColumnsReady->setAccessible(true);
        $contractColumnsReady->setValue(null);

        (new WorkspaceSkillCatalogService())->syncDefinitions();
    }

    /**
     * @param array{workspace_id:int,user_id:int,workspace_uuid:string,workspace_slug:string,workspace_name:string,membership_id:int} $seed
     * @param array<string,mixed> $config
     */
    private function installAiCoachForDashboard(array $seed, array $config = []): void
    {
        $workspaceId = (int) $seed['workspace_id'];
        $userId = (int) $seed['user_id'];
        $config = array_merge(['source' => 'test_fixture'], $config);

        Database::execute(
            "INSERT INTO workspace_skill_installs (
                workspace_id, skill_key, status, config_json, installed_by_user_id, updated_by_user_id, installed_at
             ) VALUES (?, ?, 'installed', ?, ?, ?, NOW())
             ON DUPLICATE KEY UPDATE
                status = 'installed',
                config_json = VALUES(config_json),
                updated_by_user_id = VALUES(updated_by_user_id),
                uninstalled_at = NULL,
                disabled_at = NULL",
            [
                $workspaceId,
                WorkspaceSkillCatalogService::SKILL_AI_COACH,
                json_encode($config, JSON_UNESCAPED_SLASHES),
                $userId,
                $userId,
            ]
        );
    }

    /**
     * @return array{workspace_id:int,user_id:int,workspace_uuid:string,workspace_slug:string,workspace_name:string,membership_id:int}
     */
    private function provisionWorkspace(string $slugPrefix): array
    {
        $suffix = strtolower(bin2hex(random_bytes(3)));
        $provisioned = (new WorkspaceProvisioningService())->signupWorkspaceOwner([
            'workspace_name' => 'Dashboard Popup Workspace ' . $suffix,
            'workspace_slug' => $slugPrefix . '-' . $suffix,
            'first_name' => 'Popup',
            'last_name' => 'Owner',
            'email' => $slugPrefix . '.' . $suffix . '@example.test',
            'password' => 'P@ssword123!',
            'starter_token_pack' => false,
        ]);

        $workspaceId = (int) ($provisioned['workspace_id'] ?? 0);
        $userId = (int) ($provisioned['user_id'] ?? 0);
        WorkspaceContext::activateRuntimeWorkspace($workspaceId, $userId, 'owner');

        $workspace = Database::queryOne("SELECT uuid, slug, name FROM workspaces WHERE id = ?", [$workspaceId]) ?? [];
        $membership = Database::queryOne(
            "SELECT id FROM workspace_memberships WHERE workspace_id = ? AND user_id = ? LIMIT 1",
            [$workspaceId, $userId]
        ) ?? [];

        return [
            'workspace_id' => $workspaceId,
            'user_id' => $userId,
            'workspace_uuid' => (string) ($workspace['uuid'] ?? ''),
            'workspace_slug' => (string) ($workspace['slug'] ?? ''),
            'workspace_name' => (string) ($workspace['name'] ?? ''),
            'membership_id' => (int) ($membership['id'] ?? 0),
        ];
    }

    /**
     * @param array{workspace_id:int,user_id:int,workspace_uuid:string,workspace_slug:string,workspace_name:string,membership_id:int} $seed
     * @return array<string,mixed>
     */
    private function webSession(array $seed): array
    {
        return [
            'user_id' => (int) $seed['user_id'],
            'user_uuid' => 'dashboard-popup-user',
            'user_email' => 'dashboard.popup.owner@example.test',
            'user_role' => 'admin',
            'active_workspace_id' => (int) $seed['workspace_id'],
            'active_workspace_uuid' => (string) $seed['workspace_uuid'],
            'active_workspace_slug' => (string) $seed['workspace_slug'],
            'active_workspace_name' => (string) $seed['workspace_name'],
            'active_workspace_role' => 'owner',
            'active_workspace_membership_id' => (int) $seed['membership_id'],
            'csrf_token' => 'csrf-dashboard-popup',
            '__remember_restore_attempted' => true,
        ];
    }
}
