<?php

/**
 * Inbox Triage Service
 *
 * Deterministic triage scoring and auto-apply for inbound email/whatsapp.
 */

namespace CRM\Services;

use CRM\Database;
use CRM\Modules\DealAutomationConfig;
use CRM\Modules\UserPreferences;

class InboxTriageService
{
    private DealAutomationConfig $config;
    private OwnerAssignmentService $ownerAssignment;
    private TriageTaskService $taskService;
    private UserPreferences $userPreferences;
    private ConversationIntelligenceService $conversationIntelligence;

    /** @var array<string,bool> */
    private static array $columnCache = [];

    public function __construct()
    {
        $this->config = new DealAutomationConfig();
        $this->ownerAssignment = new OwnerAssignmentService();
        $this->taskService = new TriageTaskService();
        $this->userPreferences = new UserPreferences();
        $this->conversationIntelligence = new ConversationIntelligenceService();
    }

    /**
     * Run triage for one communication id.
     *
     * @return array<string,mixed>
     */
    public function processCommunication(int $communicationId, string $appliedBy = 'system'): array
    {
        if ($communicationId <= 0 || !$this->hasCommunicationsTriageColumns()) {
            return ['status' => 'skipped', 'reason_codes' => ['triage_columns_missing']];
        }

        $cfg = $this->config->get();
        $comm = Database::queryOne(
            "SELECT id, contact_id, channel, direction, subject, body, metadata, created_at,
                    triage_priority, triage_owner_id, triage_task_id
             FROM communications
             WHERE id = ?
             LIMIT 1",
            [$communicationId]
        );
        if (!$comm) {
            return ['status' => 'skipped', 'reason_codes' => ['communication_not_found']];
        }

        $metadata = $this->decodeJson($comm['metadata'] ?? null);
        $channel = strtolower((string) ($comm['channel'] ?? ''));
        $direction = strtolower((string) ($comm['direction'] ?? ''));
        $subject = trim((string) ($comm['subject'] ?? ''));
        $body = trim((string) ($comm['body'] ?? ''));
        $text = trim($subject . "\n" . $body);
        $contactId = (int) ($comm['contact_id'] ?? 0);
        $now = date('Y-m-d H:i:s');

        $reasonCodes = [];
        if (empty($cfg['inbox_triage_enabled'])) {
            $reasonCodes[] = 'triage_disabled';
            $this->updateCommunicationTriage($communicationId, [
                'triage_priority' => null,
                'triage_score' => null,
                'triage_confidence' => null,
                'triage_status' => 'skipped',
                'triage_reason_codes' => $reasonCodes,
                'triage_decided_at' => $now,
            ]);
            $this->writeAudit([
                'communication_id' => $communicationId,
                'contact_id' => $contactId > 0 ? $contactId : null,
                'channel' => $channel,
                'decision' => 'skipped',
                'score' => null,
                'confidence' => null,
                'priority_before' => $comm['triage_priority'] ?? null,
                'priority_after' => null,
                'owner_before' => null,
                'owner_after' => null,
                'task_id' => null,
                'reason_codes' => $reasonCodes,
                'features_snapshot' => ['enabled' => false],
                'applied_by' => $appliedBy,
            ]);
            return ['status' => 'skipped', 'reason_codes' => $reasonCodes];
        }

        $channelConfig = $cfg['inbox_triage_channels'] ?? ['email' => true, 'whatsapp' => true, 'sms' => true];
        if (empty($channelConfig[$channel]) || !in_array($channel, ['email', 'whatsapp', 'sms'], true)) {
            return ['status' => 'skipped', 'reason_codes' => ['channel_not_allowed']];
        }

        if ($direction !== 'inbound') {
            return ['status' => 'skipped', 'reason_codes' => ['direction_not_inbound']];
        }

        $minLength = 8;
        $effectiveLength = mb_strlen(trim($body !== '' ? $body : $subject));
        if ($effectiveLength < $minLength) {
            $this->recordBlockedDecision($comm, $contactId, $channel, $appliedBy, ['too_short'], $metadata, 0.0, 0.0, 'low');
            return ['status' => 'blocked', 'reason_codes' => ['too_short']];
        }

        if ($this->looksAutoGenerated($channel, $subject, $body, $metadata)) {
            $this->recordBlockedDecision($comm, $contactId, $channel, $appliedBy, ['auto_generated'], $metadata, 0.0, 0.0, 'low');
            return ['status' => 'blocked', 'reason_codes' => ['auto_generated']];
        }

        $negativePhrases = $this->normalizePhraseList((string) ($cfg['inbox_triage_negative_phrase_blocklist'] ?? ''));
        $optOutPhrases = $this->normalizePhraseList((string) ($cfg['inbox_triage_opt_out_phrase_blocklist'] ?? ''));
        $lowerText = mb_strtolower($text);
        if ($this->containsAnyPhrase($lowerText, $negativePhrases)) {
            $this->recordBlockedDecision($comm, $contactId, $channel, $appliedBy, ['negative_phrase'], $metadata, 0.0, 0.0, 'low');
            return ['status' => 'blocked', 'reason_codes' => ['negative_phrase']];
        }
        if ($this->containsAnyPhrase($lowerText, $optOutPhrases)) {
            $this->recordBlockedDecision($comm, $contactId, $channel, $appliedBy, ['opt_out_phrase'], $metadata, 0.0, 0.0, 'low');
            return ['status' => 'blocked', 'reason_codes' => ['opt_out_phrase']];
        }

        $scored = $this->scoreMessage($contactId, $channel, $subject, $body, $metadata);
        $score = $scored['score'];
        $confidence = $scored['confidence'];
        $priority = $this->scoreToPriority($score);
        $reasonCodes = $scored['reason_codes'];
        $features = $scored['features'];

        $status = 'suggested';
        $ownerBefore = null;
        $ownerAfter = null;
        $taskId = null;
        $contact = $contactId > 0
            ? Database::queryOne("SELECT assigned_to FROM contacts WHERE id = ? LIMIT 1", [$contactId])
            : null;
        $ownerBefore = (int) ($contact['assigned_to'] ?? 0);

        $minConfidence = (float) ($cfg['inbox_triage_min_confidence'] ?? 0.80);
        $canAutoApply = !empty($cfg['inbox_triage_auto_apply'])
            && in_array($priority, ['urgent', 'high'], true)
            && $confidence >= $minConfidence;

        if ($canAutoApply && $contactId > 0) {
            $resolvedOwnerId = $this->ownerAssignment->resolveOwnerForContact($contactId);
            if ($resolvedOwnerId > 0 && $this->userPreferences->isInboxTriageOptOut($resolvedOwnerId)) {
                $status = 'skipped';
                $reasonCodes[] = 'owner_opt_out';
            } elseif ($resolvedOwnerId > 0) {
                $ownerAfter = $resolvedOwnerId;
                if ($ownerBefore <= 0) {
                    $this->ownerAssignment->assignContactOwner($contactId, $resolvedOwnerId);
                }

                $taskId = $this->taskService->createFollowUpTask(
                    $contactId,
                    $resolvedOwnerId,
                    $communicationId,
                    $subject !== '' ? $subject : 'Inbound ' . ucfirst($channel) . ' message',
                    (int) ($cfg['inbox_triage_task_due_hours'] ?? 24),
                    (int) ($cfg['inbox_triage_dedupe_hours'] ?? 24)
                );
                $status = 'auto_applied';
            } else {
                $status = 'skipped';
                $reasonCodes[] = 'owner_unresolved';
            }
        }

        $this->updateCommunicationTriage($communicationId, [
            'triage_priority' => $priority,
            'triage_score' => $score,
            'triage_confidence' => $confidence,
            'triage_status' => $status,
            'triage_owner_id' => $ownerAfter,
            'triage_task_id' => $taskId,
            'triage_reason_codes' => $reasonCodes,
            'triage_decided_at' => $now,
        ]);
        if ($ownerAfter > 0) {
            $this->conversationIntelligence->clearManualOwnerOverrideForCommunication($communicationId);
        }

        $this->writeAudit([
            'communication_id' => $communicationId,
            'contact_id' => $contactId > 0 ? $contactId : null,
            'channel' => $channel,
            'decision' => $status,
            'score' => $score,
            'confidence' => $confidence,
            'priority_before' => $comm['triage_priority'] ?? null,
            'priority_after' => $priority,
            'owner_before' => $ownerBefore > 0 ? $ownerBefore : null,
            'owner_after' => $ownerAfter > 0 ? $ownerAfter : null,
            'task_id' => $taskId,
            'reason_codes' => $reasonCodes,
            'features_snapshot' => $features,
            'applied_by' => $appliedBy,
        ]);
        $this->syncConversationThread($communicationId);

        return [
            'status' => $status,
            'priority' => $priority,
            'score' => $score,
            'confidence' => $confidence,
            'owner_id' => $ownerAfter,
            'task_id' => $taskId,
            'reason_codes' => $reasonCodes,
        ];
    }

    public function revertAutoApply(int $communicationId, int $actorId): bool
    {
        $comm = Database::queryOne(
            "SELECT id, contact_id, channel, triage_priority, triage_owner_id, triage_task_id
             FROM communications
             WHERE id = ?
             LIMIT 1",
            [$communicationId]
        );
        if (!$comm) {
            return false;
        }

        $last = Database::queryOne(
            "SELECT *
             FROM inbox_triage_audit
             WHERE communication_id = ? AND decision = 'auto_applied'
             ORDER BY id DESC
             LIMIT 1",
            [$communicationId]
        );
        if (!$last) {
            return false;
        }

        $ownerBefore = (int) ($last['owner_before'] ?? 0);
        $ownerAfter = (int) ($last['owner_after'] ?? 0);
        $taskId = (int) ($comm['triage_task_id'] ?? 0);
        $contactId = (int) ($comm['contact_id'] ?? 0);

        if ($taskId > 0) {
            Database::execute(
                "UPDATE tasks
                 SET status = 'cancelled'
                 WHERE id = ?
                   AND status IN ('pending','in_progress')
                   AND description LIKE ?",
                [$taskId, '%[INBOX_TRIAGE]%']
            );
        }

        if ($contactId > 0 && $ownerBefore > 0 && $ownerAfter > 0) {
            Database::execute(
                "UPDATE contacts
                 SET assigned_to = ?
                 WHERE id = ? AND assigned_to = ?",
                [$ownerBefore, $contactId, $ownerAfter]
            );
        }

        $reasonCodes = ['reverted_by_user'];
        $this->updateCommunicationTriage($communicationId, [
            'triage_priority' => $last['priority_before'] ?: null,
            'triage_status' => 'skipped',
            'triage_owner_id' => $ownerBefore > 0 ? $ownerBefore : null,
            'triage_task_id' => null,
            'triage_reason_codes' => $reasonCodes,
            'triage_decided_at' => date('Y-m-d H:i:s'),
        ]);
        if ($ownerBefore > 0) {
            $this->conversationIntelligence->clearManualOwnerOverrideForCommunication($communicationId);
        }

        $this->writeAudit([
            'communication_id' => $communicationId,
            'contact_id' => $contactId > 0 ? $contactId : null,
            'channel' => (string) ($comm['channel'] ?? ''),
            'decision' => 'revert_auto_apply',
            'score' => null,
            'confidence' => null,
            'priority_before' => $comm['triage_priority'] ?? null,
            'priority_after' => $last['priority_before'] ?: null,
            'owner_before' => $ownerAfter > 0 ? $ownerAfter : null,
            'owner_after' => $ownerBefore > 0 ? $ownerBefore : null,
            'task_id' => $taskId > 0 ? $taskId : null,
            'reason_codes' => $reasonCodes,
            'features_snapshot' => ['actor_id' => $actorId],
            'applied_by' => (string) $actorId,
        ]);
        $this->syncConversationThread($communicationId);
        return true;
    }

    public function acceptSuggestion(int $communicationId, int $actorId): bool
    {
        $comm = Database::queryOne(
            "SELECT id, contact_id, channel, subject, triage_priority, triage_score, triage_confidence, triage_status
             FROM communications
             WHERE id = ?
             LIMIT 1",
            [$communicationId]
        );
        if (!$comm || ($comm['triage_status'] ?? '') !== 'suggested') {
            return false;
        }

        $contactId = (int) ($comm['contact_id'] ?? 0);
        if ($contactId <= 0) {
            return false;
        }

        $ownerId = $this->ownerAssignment->resolveOwnerForContact($contactId);
        if ($ownerId <= 0 || $this->userPreferences->isInboxTriageOptOut($ownerId)) {
            return false;
        }

        $cfg = $this->config->get();
        $taskId = $this->taskService->createFollowUpTask(
            $contactId,
            $ownerId,
            $communicationId,
            (string) ($comm['subject'] ?? 'Inbound message'),
            (int) ($cfg['inbox_triage_task_due_hours'] ?? 24),
            (int) ($cfg['inbox_triage_dedupe_hours'] ?? 24)
        );

        $this->updateCommunicationTriage($communicationId, [
            'triage_status' => 'auto_applied',
            'triage_owner_id' => $ownerId,
            'triage_task_id' => $taskId > 0 ? $taskId : null,
            'triage_reason_codes' => ['accepted_by_user'],
            'triage_decided_at' => date('Y-m-d H:i:s'),
        ]);
        $this->conversationIntelligence->clearManualOwnerOverrideForCommunication($communicationId);

        $this->writeAudit([
            'communication_id' => $communicationId,
            'contact_id' => $contactId,
            'channel' => (string) ($comm['channel'] ?? ''),
            'decision' => 'accept_suggestion',
            'score' => isset($comm['triage_score']) ? (float) $comm['triage_score'] : null,
            'confidence' => isset($comm['triage_confidence']) ? (float) $comm['triage_confidence'] : null,
            'priority_before' => $comm['triage_priority'] ?? null,
            'priority_after' => $comm['triage_priority'] ?? null,
            'owner_before' => null,
            'owner_after' => $ownerId,
            'task_id' => $taskId > 0 ? $taskId : null,
            'reason_codes' => ['accepted_by_user'],
            'features_snapshot' => ['actor_id' => $actorId],
            'applied_by' => (string) $actorId,
        ]);
        $this->syncConversationThread($communicationId);

        return true;
    }

    public function snoozeTask(int $communicationId, int $hours, int $actorId): bool
    {
        $hours = max(1, min(168, $hours));
        $comm = Database::queryOne(
            "SELECT id, contact_id, channel, triage_task_id
             FROM communications
             WHERE id = ?
             LIMIT 1",
            [$communicationId]
        );
        if (!$comm) {
            return false;
        }
        $taskId = (int) ($comm['triage_task_id'] ?? 0);
        if ($taskId <= 0) {
            return false;
        }

        $updated = Database::execute(
            "UPDATE tasks
             SET due_date = DATE_ADD(COALESCE(due_date, NOW()), INTERVAL ? HOUR)
             WHERE id = ?",
            [$hours, $taskId]
        );
        if ($updated <= 0) {
            return false;
        }

        $this->writeAudit([
            'communication_id' => $communicationId,
            'contact_id' => (int) ($comm['contact_id'] ?? 0),
            'channel' => (string) ($comm['channel'] ?? ''),
            'decision' => 'snooze_task',
            'score' => null,
            'confidence' => null,
            'priority_before' => null,
            'priority_after' => null,
            'owner_before' => null,
            'owner_after' => null,
            'task_id' => $taskId,
            'reason_codes' => ['task_snoozed'],
            'features_snapshot' => ['hours' => $hours, 'actor_id' => $actorId],
            'applied_by' => (string) $actorId,
        ]);
        return true;
    }

    public function reassignOwner(int $communicationId, int $newOwnerId, int $actorId): bool
    {
        if ($newOwnerId <= 0) {
            return false;
        }
        $comm = Database::queryOne(
            "SELECT id, contact_id, channel, triage_owner_id, triage_task_id
             FROM communications
             WHERE id = ?
             LIMIT 1",
            [$communicationId]
        );
        if (!$comm) {
            return false;
        }
        $oldOwnerId = (int) ($comm['triage_owner_id'] ?? 0);

        $this->updateCommunicationTriage($communicationId, [
            'triage_owner_id' => $newOwnerId,
            'triage_reason_codes' => ['owner_reassigned'],
            'triage_decided_at' => date('Y-m-d H:i:s'),
        ]);
        $this->conversationIntelligence->clearManualOwnerOverrideForCommunication($communicationId);

        $taskId = (int) ($comm['triage_task_id'] ?? 0);
        if ($taskId > 0) {
            Database::execute("UPDATE tasks SET assigned_to = ? WHERE id = ?", [$newOwnerId, $taskId]);
        }

        $contactId = (int) ($comm['contact_id'] ?? 0);
        if ($contactId > 0) {
            if ($oldOwnerId > 0) {
                Database::execute(
                    "UPDATE contacts SET assigned_to = ? WHERE id = ? AND assigned_to = ?",
                    [$newOwnerId, $contactId, $oldOwnerId]
                );
            } else {
                Database::execute(
                    "UPDATE contacts SET assigned_to = ? WHERE id = ? AND (assigned_to IS NULL OR assigned_to = 0)",
                    [$newOwnerId, $contactId]
                );
            }
        }

        $this->writeAudit([
            'communication_id' => $communicationId,
            'contact_id' => $contactId > 0 ? $contactId : null,
            'channel' => (string) ($comm['channel'] ?? ''),
            'decision' => 'reassign_owner',
            'score' => null,
            'confidence' => null,
            'priority_before' => null,
            'priority_after' => null,
            'owner_before' => $oldOwnerId > 0 ? $oldOwnerId : null,
            'owner_after' => $newOwnerId,
            'task_id' => $taskId > 0 ? $taskId : null,
            'reason_codes' => ['owner_reassigned'],
            'features_snapshot' => ['actor_id' => $actorId],
            'applied_by' => (string) $actorId,
        ]);
        $this->syncConversationThread($communicationId);

        return true;
    }

    /**
     * @return array<string,mixed>
     */
    public function getMetrics(int $days = 14): array
    {
        $days = max(1, min(90, $days));

        $overview = Database::queryOne(
            "SELECT
                SUM(CASE WHEN triage_status = 'auto_applied' THEN 1 ELSE 0 END) AS auto_applied_count,
                SUM(CASE WHEN triage_status = 'blocked' THEN 1 ELSE 0 END) AS blocked_count,
                SUM(CASE WHEN triage_status = 'suggested' THEN 1 ELSE 0 END) AS suggested_count
             FROM communications
             WHERE direction = 'inbound'
               AND channel IN ('email', 'whatsapp')
               AND created_at >= DATE_SUB(NOW(), INTERVAL ? DAY)",
            [$days]
        ) ?: [];

        $revertRate = Database::queryOne(
            "SELECT
                SUM(CASE WHEN decision = 'revert_auto_apply' THEN 1 ELSE 0 END) AS reverted,
                SUM(CASE WHEN decision = 'auto_applied' THEN 1 ELSE 0 END) AS applied
             FROM inbox_triage_audit
             WHERE created_at >= DATE_SUB(NOW(), INTERVAL ? DAY)",
            [$days]
        ) ?: ['reverted' => 0, 'applied' => 0];

        $conversion48h = Database::queryOne(
            "SELECT COUNT(*) AS converted
             FROM communications c
             WHERE c.direction = 'inbound'
               AND c.channel IN ('email','whatsapp')
               AND c.created_at >= DATE_SUB(NOW(), INTERVAL ? DAY)
               AND EXISTS (
                   SELECT 1 FROM tasks t
                   WHERE t.contact_id = c.contact_id
                     AND t.description LIKE '%[INBOX_TRIAGE]%'
                     AND t.status = 'completed'
                     AND t.completed_at IS NOT NULL
                     AND t.completed_at <= DATE_ADD(c.created_at, INTERVAL 48 HOUR)
               )",
            [$days]
        ) ?: ['converted' => 0];

        $conversion7d = Database::queryOne(
            "SELECT COUNT(*) AS converted
             FROM communications c
             WHERE c.direction = 'inbound'
               AND c.channel IN ('email','whatsapp')
               AND c.created_at >= DATE_SUB(NOW(), INTERVAL ? DAY)
               AND EXISTS (
                   SELECT 1
                   FROM deals d
                   WHERE d.contact_id = c.contact_id
                     AND d.updated_at <= DATE_ADD(c.created_at, INTERVAL 7 DAY)
                     AND (d.created_at >= c.created_at OR d.stage IN ('qualification','proposal','negotiation','closed_won'))
               )",
            [$days]
        ) ?: ['converted' => 0];

        $blockedReasons = Database::query(
            "SELECT jt.reason_code, COUNT(*) AS count
             FROM inbox_triage_audit a
             JOIN JSON_TABLE(a.reason_codes, '$[*]' COLUMNS(reason_code VARCHAR(64) PATH '$')) jt
             WHERE a.created_at >= DATE_SUB(NOW(), INTERVAL ? DAY)
               AND a.decision IN ('blocked','skipped')
             GROUP BY jt.reason_code
             ORDER BY count DESC
             LIMIT 10",
            [$days]
        );

        return [
            'window_days' => $days,
            'overview' => [
                'auto_applied_count' => (int) ($overview['auto_applied_count'] ?? 0),
                'blocked_count' => (int) ($overview['blocked_count'] ?? 0),
                'suggested_count' => (int) ($overview['suggested_count'] ?? 0),
            ],
            'revert_rate' => [
                'reverted' => (int) ($revertRate['reverted'] ?? 0),
                'applied' => (int) ($revertRate['applied'] ?? 0),
                'rate' => ((int) ($revertRate['applied'] ?? 0)) > 0
                    ? round(((int) ($revertRate['reverted'] ?? 0) / (int) ($revertRate['applied'] ?? 0)) * 100, 2)
                    : 0.0,
            ],
            'conversion_proxy' => [
                'follow_up_completed_48h' => (int) ($conversion48h['converted'] ?? 0),
                'deal_created_or_advanced_7d' => (int) ($conversion7d['converted'] ?? 0),
            ],
            'blocked_reasons' => $blockedReasons,
        ];
    }

    /**
     * @return array<string,mixed>
     */
    private function scoreMessage(int $contactId, string $channel, string $subject, string $body, array $metadata): array
    {
        $reasonCodes = [];
        $features = [];
        $score = 0.0;

        $intent = strtolower((string) ($metadata['intent']['intent'] ?? $metadata['intent'] ?? ''));
        $intentWeight = [
            'purchase' => 35,
            'booking' => 30,
            'inquiry' => 25,
            'information' => 18,
            'support' => 8,
            'complaint' => -30,
            'cancellation' => -35,
        ];
        if ($intent !== '') {
            $score += (float) ($intentWeight[$intent] ?? 8);
            $reasonCodes[] = 'intent_' . $intent;
        }
        $features['intent'] = $intent;

        $sentiment = strtolower((string) ($metadata['sentiment']['sentiment'] ?? 'neutral'));
        $sentimentScore = (float) ($metadata['sentiment']['score'] ?? 0.0);
        if ($sentiment === 'positive' || $sentimentScore > 0.15) {
            $score += 15;
            $reasonCodes[] = 'sentiment_positive';
        } elseif ($sentiment === 'negative' || $sentimentScore < -0.15) {
            $score -= 20;
            $reasonCodes[] = 'sentiment_negative';
        } else {
            $score += 8;
            $reasonCodes[] = 'sentiment_neutral';
        }
        $features['sentiment'] = $sentiment;
        $features['sentiment_score'] = $sentimentScore;

        $text = trim($subject . "\n" . $body);
        $textLower = mb_strtolower($text);
        $length = mb_strlen(trim($body !== '' ? $body : $subject));
        if ($length >= 40) {
            $score += 10;
            $reasonCodes[] = 'length_substantial';
        } elseif ($length >= 20) {
            $score += 6;
            $reasonCodes[] = 'length_meaningful';
        } else {
            $score -= 5;
            $reasonCodes[] = 'length_short';
        }
        $features['length'] = $length;

        if (mb_strpos($text, '?') !== false) {
            $score += 10;
            $reasonCodes[] = 'has_question';
        }
        $engagementTerms = ['price', 'cost', 'quote', 'demo', 'meeting', 'call', 'interested', 'can we', 'how much'];
        if ($this->containsAnyPhrase($textLower, $engagementTerms)) {
            $score += 8;
            $reasonCodes[] = 'engagement_signal';
        }

        $openDealCount = 0;
        if ($contactId > 0) {
            $open = Database::queryOne(
                "SELECT COUNT(*) AS c
                 FROM deals
                 WHERE contact_id = ?
                   AND stage IN ('prospecting','qualification','proposal','negotiation')",
                [$contactId]
            );
            $openDealCount = (int) ($open['c'] ?? 0);
            if ($openDealCount > 0) {
                $score += 8;
                $reasonCodes[] = 'open_deal_context';
            }

            $recentUnread = Database::queryOne(
                "SELECT COUNT(*) AS c
                 FROM communications
                 WHERE contact_id = ?
                   AND direction = 'inbound'
                   AND channel = ?
                   AND read_at IS NULL
                   AND created_at >= DATE_SUB(NOW(), INTERVAL 48 HOUR)",
                [$contactId, $channel]
            );
            if ((int) ($recentUnread['c'] ?? 0) > 1) {
                $score += 6;
                $reasonCodes[] = 'followup_backlog';
            }
        }
        $features['open_deals'] = $openDealCount;

        $score = max(0.0, min(100.0, $score));
        $confidence = 0.55;
        if ($intent !== '') {
            $confidence += 0.12;
        }
        if (isset($metadata['sentiment'])) {
            $confidence += 0.08;
        }
        if ($length >= 20) {
            $confidence += 0.08;
        }
        if (mb_strpos($text, '?') !== false) {
            $confidence += 0.07;
        }
        if ($openDealCount > 0) {
            $confidence += 0.05;
        }
        if ($score < 35) {
            $confidence -= 0.10;
        }
        $confidence = max(0.0, min(1.0, $confidence));

        return [
            'score' => round($score, 2),
            'confidence' => round($confidence, 2),
            'reason_codes' => array_values(array_unique($reasonCodes)),
            'features' => $features,
        ];
    }

    private function scoreToPriority(float $score): string
    {
        if ($score >= 85) {
            return 'urgent';
        }
        if ($score >= 70) {
            return 'high';
        }
        if ($score >= 45) {
            return 'medium';
        }
        return 'low';
    }

    /**
     * @param array<string,mixed> $comm
     * @param array<string,mixed> $metadata
     * @param array<int,string> $reasonCodes
     */
    private function recordBlockedDecision(array $comm, int $contactId, string $channel, string $appliedBy, array $reasonCodes, array $metadata, float $score, float $confidence, string $priority): void
    {
        $this->updateCommunicationTriage((int) $comm['id'], [
            'triage_priority' => $priority,
            'triage_score' => $score,
            'triage_confidence' => $confidence,
            'triage_status' => 'blocked',
            'triage_owner_id' => null,
            'triage_task_id' => null,
            'triage_reason_codes' => $reasonCodes,
            'triage_decided_at' => date('Y-m-d H:i:s'),
        ]);
        $this->writeAudit([
            'communication_id' => (int) $comm['id'],
            'contact_id' => $contactId > 0 ? $contactId : null,
            'channel' => $channel,
            'decision' => 'blocked',
            'score' => $score,
            'confidence' => $confidence,
            'priority_before' => $comm['triage_priority'] ?? null,
            'priority_after' => $priority,
            'owner_before' => null,
            'owner_after' => null,
            'task_id' => null,
            'reason_codes' => $reasonCodes,
            'features_snapshot' => $metadata,
            'applied_by' => $appliedBy,
        ]);
    }

    /**
     * @param array<string,mixed> $data
     */
    private function updateCommunicationTriage(int $communicationId, array $data): void
    {
        $fields = [];
        $params = [];

        $map = [
            'triage_priority' => 'triage_priority',
            'triage_score' => 'triage_score',
            'triage_confidence' => 'triage_confidence',
            'triage_status' => 'triage_status',
            'triage_owner_id' => 'triage_owner_id',
            'triage_task_id' => 'triage_task_id',
            'triage_reason_codes' => 'triage_reason_codes',
            'triage_decided_at' => 'triage_decided_at',
        ];

        foreach ($map as $key => $column) {
            if (!array_key_exists($key, $data) || !$this->columnExists('communications', $column)) {
                continue;
            }
            if ($key === 'triage_reason_codes') {
                $fields[] = $column . " = ?";
                $params[] = json_encode(array_values((array) $data[$key]));
                continue;
            }
            $fields[] = $column . " = ?";
            $params[] = $data[$key];
        }

        if (empty($fields)) {
            return;
        }

        $params[] = $communicationId;
        Database::execute(
            "UPDATE communications SET " . implode(', ', $fields) . " WHERE id = ?",
            $params
        );
    }

    /**
     * @param array<string,mixed> $audit
     */
    private function writeAudit(array $audit): void
    {
        if (!$this->tableExists('inbox_triage_audit')) {
            return;
        }

        try {
            Database::execute(
                "INSERT INTO inbox_triage_audit
                 (communication_id, contact_id, channel, decision, score, confidence,
                  priority_before, priority_after, owner_before, owner_after, task_id,
                  reason_codes, features_snapshot, applied_by)
                 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                [
                    $audit['communication_id'] ?? null,
                    $audit['contact_id'] ?? null,
                    $audit['channel'] ?? null,
                    $audit['decision'] ?? null,
                    $audit['score'] ?? null,
                    $audit['confidence'] ?? null,
                    $audit['priority_before'] ?? null,
                    $audit['priority_after'] ?? null,
                    $audit['owner_before'] ?? null,
                    $audit['owner_after'] ?? null,
                    $audit['task_id'] ?? null,
                    json_encode($audit['reason_codes'] ?? []),
                    json_encode($audit['features_snapshot'] ?? []),
                    (string) ($audit['applied_by'] ?? 'system'),
                ]
            );
        } catch (\Throwable $e) {
            error_log('InboxTriageService audit write failed: ' . $e->getMessage());
        }
    }

    private function looksAutoGenerated(string $channel, string $subject, string $body, array $metadata): bool
    {
        if ($channel !== 'email') {
            return false;
        }

        $text = mb_strtolower(trim($subject . ' ' . $body));
        $fromEmail = mb_strtolower((string) ($metadata['from_email'] ?? ''));
        if ($fromEmail !== '' && (mb_strpos($fromEmail, 'no-reply') !== false || mb_strpos($fromEmail, 'noreply') !== false)) {
            return true;
        }

        $patterns = [
            'out of office',
            'automatic reply',
            'auto reply',
            'autoreply',
            'vacation',
            'away from office',
            'delivery status notification',
            'undeliverable',
            'mailer-daemon',
            'delivery has failed',
        ];
        return $this->containsAnyPhrase($text, $patterns);
    }

    /**
     * @param array<int,string> $phrases
     */
    private function containsAnyPhrase(string $text, array $phrases): bool
    {
        foreach ($phrases as $phrase) {
            $phrase = trim(mb_strtolower((string) $phrase));
            if ($phrase !== '' && mb_strpos($text, $phrase) !== false) {
                return true;
            }
        }
        return false;
    }

    /**
     * @return array<int,string>
     */
    private function normalizePhraseList(string $text): array
    {
        if ($text === '') {
            return [];
        }
        $lines = preg_split('/[\r\n,]+/', $text) ?: [];
        $result = [];
        foreach ($lines as $line) {
            $line = trim(mb_strtolower($line));
            if ($line !== '') {
                $result[] = $line;
            }
        }
        return array_values(array_unique($result));
    }

    /**
     * @return array<string,mixed>
     */
    private function decodeJson($value): array
    {
        if (is_array($value)) {
            return $value;
        }
        if (!is_string($value) || $value === '') {
            return [];
        }
        $decoded = json_decode($value, true);
        return is_array($decoded) ? $decoded : [];
    }

    private function hasCommunicationsTriageColumns(): bool
    {
        return $this->columnExists('communications', 'triage_priority')
            && $this->columnExists('communications', 'triage_status');
    }

    private function syncConversationThread(int $communicationId): void
    {
        if ($communicationId <= 0) {
            return;
        }
        try {
            $this->conversationIntelligence->syncForCommunication($communicationId);
        } catch (\Throwable $e) {
            error_log('InboxTriageService thread sync failed: ' . $e->getMessage());
        }
    }

    private function tableExists(string $table): bool
    {
        $cacheKey = 'table:' . $table;
        if (array_key_exists($cacheKey, self::$columnCache)) {
            return self::$columnCache[$cacheKey];
        }
        try {
            $row = Database::queryOne(
                "SELECT COUNT(*) AS c
                 FROM information_schema.TABLES
                 WHERE TABLE_SCHEMA = DATABASE()
                   AND TABLE_NAME = ?",
                [$table]
            );
            self::$columnCache[$cacheKey] = ((int) ($row['c'] ?? 0)) > 0;
        } catch (\Throwable $e) {
            self::$columnCache[$cacheKey] = false;
        }
        return self::$columnCache[$cacheKey];
    }

    private function columnExists(string $table, string $column): bool
    {
        $cacheKey = $table . '.' . $column;
        if (array_key_exists($cacheKey, self::$columnCache)) {
            return self::$columnCache[$cacheKey];
        }
        try {
            $row = Database::queryOne(
                "SELECT COUNT(*) AS c
                 FROM information_schema.COLUMNS
                 WHERE TABLE_SCHEMA = DATABASE()
                   AND TABLE_NAME = ?
                   AND COLUMN_NAME = ?",
                [$table, $column]
            );
            self::$columnCache[$cacheKey] = ((int) ($row['c'] ?? 0)) > 0;
        } catch (\Throwable $e) {
            self::$columnCache[$cacheKey] = false;
        }
        return self::$columnCache[$cacheKey];
    }
}
