CREATE TABLE IF NOT EXISTS ai_decision_outcomes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    guidance_run_id INT NULL,
    assistant_run_id INT NULL,
    commercial_run_id INT NULL,
    approval_id INT NULL,
    task_id INT NULL,
    user_id INT NULL,
    surface VARCHAR(50) NOT NULL,
    decision_type VARCHAR(32) NOT NULL,
    action_type VARCHAR(100) NOT NULL,
    predicted_confidence DECIMAL(6,4) NULL,
    context_quality_score DECIMAL(6,4) NULL,
    goal_relevance_score DECIMAL(6,4) NULL,
    policy_decision VARCHAR(32) NULL,
    threshold_snapshot_json JSON NULL,
    outcome_label VARCHAR(32) NOT NULL,
    outcome_score DECIMAL(6,4) NOT NULL DEFAULT 0,
    outcome_metadata_json JSON NULL,
    measured_at DATETIME NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_ai_decision_outcomes_surface_action_measured (surface, action_type, measured_at),
    INDEX idx_ai_decision_outcomes_guidance_run (guidance_run_id),
    INDEX idx_ai_decision_outcomes_assistant_run (assistant_run_id),
    INDEX idx_ai_decision_outcomes_commercial_run (commercial_run_id),
    INDEX idx_ai_decision_outcomes_approval (approval_id),
    INDEX idx_ai_decision_outcomes_task (task_id),
    INDEX idx_ai_decision_outcomes_label_measured (outcome_label, measured_at)
);

CREATE TABLE IF NOT EXISTS ai_threshold_tuning_log (
    id INT AUTO_INCREMENT PRIMARY KEY,
    surface VARCHAR(50) NOT NULL,
    action_type VARCHAR(100) NOT NULL,
    threshold_key VARCHAR(100) NOT NULL,
    scope_type VARCHAR(32) NOT NULL DEFAULT 'global',
    previous_value DECIMAL(8,4) NOT NULL,
    recommended_value DECIMAL(8,4) NOT NULL,
    applied_value DECIMAL(8,4) NOT NULL,
    sample_size INT NOT NULL DEFAULT 0,
    observed_precision DECIMAL(8,4) NOT NULL DEFAULT 0,
    observed_edit_rate DECIMAL(8,4) NOT NULL DEFAULT 0,
    observed_rejection_rate DECIMAL(8,4) NOT NULL DEFAULT 0,
    observed_reversal_rate DECIMAL(8,4) NOT NULL DEFAULT 0,
    observed_failure_rate DECIMAL(8,4) NOT NULL DEFAULT 0,
    change_reason_summary TEXT NULL,
    calibration_snapshot_json JSON NULL,
    applied_automatically TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_ai_threshold_tuning_surface_action_created (surface, action_type, created_at),
    INDEX idx_ai_threshold_tuning_key_created (threshold_key, created_at)
);
