CREATE TABLE IF NOT EXISTS ai_operator_demonstrations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tenant_key VARCHAR(128) NOT NULL,
    actor_user_id INT NULL,
    actor_type VARCHAR(32) NOT NULL DEFAULT 'system',
    source_surface VARCHAR(64) NOT NULL,
    domain_key VARCHAR(64) NOT NULL DEFAULT 'commercial_mvp',
    entity_type VARCHAR(64) NOT NULL,
    entity_id INT NULL,
    related_entity_type VARCHAR(64) NULL,
    related_entity_id INT NULL,
    action_key VARCHAR(128) NOT NULL,
    prior_state_json JSON NULL,
    action_payload_json JSON NULL,
    outcome_state_json JSON NULL,
    outcome_label VARCHAR(32) NOT NULL DEFAULT 'observed',
    free_text_reason TEXT NULL,
    metadata_json JSON NULL,
    demonstration_hash CHAR(40) NOT NULL,
    linked_commercial_run_id INT NULL,
    linked_approval_id INT NULL,
    linked_task_id INT NULL,
    was_successful TINYINT(1) NOT NULL DEFAULT 0,
    was_reversed TINYINT(1) NOT NULL DEFAULT 0,
    was_edited TINYINT(1) NOT NULL DEFAULT 0,
    observed_at DATETIME NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_ai_operator_demonstration_hash (demonstration_hash),
    INDEX idx_ai_operator_demo_tenant_domain_action (tenant_key, domain_key, action_key, observed_at),
    INDEX idx_ai_operator_demo_surface_entity (source_surface, entity_type, entity_id),
    INDEX idx_ai_operator_demo_actor (actor_user_id, observed_at),
    CONSTRAINT fk_ai_operator_demo_actor_user FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_ai_operator_demo_commercial_run FOREIGN KEY (linked_commercial_run_id) REFERENCES commercial_automation_runs(id) ON DELETE SET NULL,
    CONSTRAINT fk_ai_operator_demo_approval FOREIGN KEY (linked_approval_id) REFERENCES commercial_automation_approvals(id) ON DELETE SET NULL,
    CONSTRAINT fk_ai_operator_demo_task FOREIGN KEY (linked_task_id) REFERENCES tasks(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_tenant_policy_memory (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tenant_key VARCHAR(128) NOT NULL,
    scope_key VARCHAR(64) NOT NULL DEFAULT 'commercial_mvp',
    memory_key VARCHAR(128) NOT NULL,
    memory_value_json JSON NULL,
    evidence_count INT NOT NULL DEFAULT 0,
    success_count INT NOT NULL DEFAULT 0,
    reversal_count INT NOT NULL DEFAULT 0,
    edit_count INT NOT NULL DEFAULT 0,
    last_observed_at DATETIME NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_ai_tenant_policy_memory (tenant_key, scope_key, memory_key),
    INDEX idx_ai_tenant_policy_scope (tenant_key, scope_key, last_observed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_autonomy_eval_runs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tenant_key VARCHAR(128) NOT NULL,
    domain_key VARCHAR(64) NOT NULL,
    autonomy_mode VARCHAR(32) NOT NULL,
    run_status VARCHAR(32) NOT NULL DEFAULT 'running',
    scenario_count INT NOT NULL DEFAULT 0,
    metrics_json JSON NULL,
    summary_json JSON NULL,
    started_at DATETIME NOT NULL,
    completed_at DATETIME NULL,
    created_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_ai_autonomy_eval_tenant_domain (tenant_key, domain_key, started_at),
    INDEX idx_ai_autonomy_eval_status (run_status, started_at),
    CONSTRAINT fk_ai_autonomy_eval_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_action_similarity_index (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tenant_key VARCHAR(128) NOT NULL,
    domain_key VARCHAR(64) NOT NULL,
    action_key VARCHAR(128) NOT NULL,
    demonstration_id INT NOT NULL,
    feature_fingerprint CHAR(40) NOT NULL,
    feature_summary_json JSON NULL,
    outcome_label VARCHAR(32) NOT NULL DEFAULT 'observed',
    score DECIMAL(6,4) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_ai_action_similarity_demo (demonstration_id),
    INDEX idx_ai_action_similarity_lookup (tenant_key, domain_key, action_key, outcome_label),
    INDEX idx_ai_action_similarity_fingerprint (feature_fingerprint),
    CONSTRAINT fk_ai_action_similarity_demo FOREIGN KEY (demonstration_id) REFERENCES ai_operator_demonstrations(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
