CREATE TABLE IF NOT EXISTS ai_cross_domain_runs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    tenant_key VARCHAR(190) NOT NULL,
    objective_key VARCHAR(100) NOT NULL,
    primary_entity_type VARCHAR(100) NOT NULL,
    primary_entity_id BIGINT UNSIGNED NOT NULL,
    related_entities_json JSON DEFAULT NULL,
    execution_mode VARCHAR(32) NOT NULL DEFAULT 'plan_only',
    run_status ENUM('planned','running','blocked','approval_required','completed','failed','canceled') NOT NULL DEFAULT 'planned',
    reason_note VARCHAR(255) DEFAULT NULL,
    plan_json JSON DEFAULT NULL,
    summary_json JSON DEFAULT NULL,
    created_by BIGINT UNSIGNED DEFAULT NULL,
    started_at DATETIME DEFAULT NULL,
    completed_at DATETIME DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_ai_cross_domain_runs_scope (tenant_key, run_status, created_at),
    KEY idx_ai_cross_domain_runs_objective (objective_key, primary_entity_type, primary_entity_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_cross_domain_steps (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    run_id BIGINT UNSIGNED NOT NULL,
    step_order INT NOT NULL,
    domain_key VARCHAR(100) NOT NULL,
    action_key VARCHAR(100) NOT NULL,
    target_entity_type VARCHAR(100) NOT NULL,
    target_entity_id BIGINT UNSIGNED NOT NULL,
    depends_on_step_id BIGINT UNSIGNED DEFAULT NULL,
    customer_facing TINYINT(1) NOT NULL DEFAULT 0,
    assistant_confidence DECIMAL(6,4) DEFAULT NULL,
    precheck_status VARCHAR(32) NOT NULL DEFAULT 'pending',
    step_status ENUM('planned','running','blocked','approval_required','completed','failed','skipped','canceled') NOT NULL DEFAULT 'planned',
    linked_incident_id BIGINT UNSIGNED DEFAULT NULL,
    linked_recovery_queue_id BIGINT UNSIGNED DEFAULT NULL,
    linked_domain_run_id BIGINT UNSIGNED DEFAULT NULL,
    plan_context_json JSON DEFAULT NULL,
    result_json JSON DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_ai_cross_domain_steps_run (run_id, step_order),
    KEY idx_ai_cross_domain_steps_status (step_status, domain_key),
    KEY idx_ai_cross_domain_steps_dependency (depends_on_step_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
