CREATE TABLE IF NOT EXISTS workspace_whatsapp_integrations (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id INT NOT NULL,
    connected_by_user_id INT NULL,
    meta_business_id VARCHAR(191) NULL,
    whatsapp_business_account_id VARCHAR(191) NULL,
    phone_number_id VARCHAR(191) NULL,
    display_phone_number VARCHAR(64) NULL,
    verified_name VARCHAR(191) NULL,
    access_token MEDIUMTEXT NULL,
    token_expires_at DATETIME NULL,
    connection_status ENUM('connecting','connected','needs_attention','disconnected') NOT NULL DEFAULT 'connecting',
    last_error TEXT NULL,
    settings_json JSON NULL,
    connected_at DATETIME NULL,
    disconnected_at DATETIME NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_workspace_whatsapp_integrations_workspace (workspace_id),
    KEY idx_workspace_whatsapp_integrations_status (connection_status),
    KEY idx_workspace_whatsapp_integrations_phone (phone_number_id),
    CONSTRAINT fk_workspace_whatsapp_integrations_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_workspace_whatsapp_integrations_user FOREIGN KEY (connected_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
