-- Marketing Phase 17: manual-first email campaign execution planning.

CREATE TABLE IF NOT EXISTS marketing_email_campaign_runs (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id INT NOT NULL,
    uuid CHAR(36) NOT NULL,
    name VARCHAR(180) NOT NULL,
    content_item_id INT NULL,
    campaign_id INT NULL,
    email_template_id INT NULL,
    subject VARCHAR(255) NULL,
    preview_text VARCHAR(255) NULL,
    body_snapshot MEDIUMTEXT NULL,
    segment_name VARCHAR(160) NULL,
    segment_snapshot_json JSON NULL,
    recipient_count INT NOT NULL DEFAULT 0,
    send_checklist_json JSON NULL,
    export_bundle_json JSON NULL,
    performance_json JSON NULL,
    scheduled_at DATETIME NULL,
    exported_at DATETIME NULL,
    status ENUM('draft','ready','exported','archived') NOT NULL DEFAULT 'draft',
    metadata_json JSON NULL,
    created_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_marketing_email_runs_uuid (uuid),
    KEY idx_marketing_email_runs_workspace_status (workspace_id, status, updated_at),
    KEY idx_marketing_email_runs_workspace_campaign (workspace_id, campaign_id),
    KEY idx_marketing_email_runs_workspace_content (workspace_id, content_item_id),
    KEY idx_marketing_email_runs_workspace_scheduled (workspace_id, scheduled_at),
    CONSTRAINT fk_marketing_email_runs_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_marketing_email_runs_content FOREIGN KEY (content_item_id) REFERENCES marketing_content_items(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_email_runs_campaign FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_email_runs_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
