-- Marketing Phase 21: creative asset production and usage readiness.

CREATE TABLE IF NOT EXISTS marketing_creative_briefs (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id INT NOT NULL,
    content_item_id INT NULL,
    campaign_id INT NULL,
    uuid CHAR(36) NOT NULL,
    title VARCHAR(255) NOT NULL,
    asset_type ENUM('image','video','document','audio','link','other') NOT NULL DEFAULT 'image',
    channel VARCHAR(80) NULL,
    objective TEXT NULL,
    specs_json JSON NULL,
    status ENUM('draft','ready','in_production','completed','archived') NOT NULL DEFAULT 'draft',
    owner_user_id INT NULL,
    metadata_json JSON NULL,
    created_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_marketing_creative_briefs_uuid (uuid),
    KEY idx_marketing_creative_briefs_workspace_status (workspace_id, status, updated_at),
    KEY idx_marketing_creative_briefs_workspace_content (workspace_id, content_item_id),
    KEY idx_marketing_creative_briefs_workspace_campaign (workspace_id, campaign_id),
    CONSTRAINT fk_marketing_creative_briefs_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_marketing_creative_briefs_content FOREIGN KEY (content_item_id) REFERENCES marketing_content_items(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_creative_briefs_campaign FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_creative_briefs_owner FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_creative_briefs_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS marketing_asset_requests (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id INT NOT NULL,
    creative_brief_id INT NULL,
    content_item_id INT NULL,
    uuid CHAR(36) NOT NULL,
    title VARCHAR(255) NOT NULL,
    requested_asset_type ENUM('image','video','document','audio','link','other') NOT NULL DEFAULT 'image',
    channel VARCHAR(80) NULL,
    description TEXT NULL,
    due_at DATETIME NULL,
    status ENUM('requested','in_progress','ready','approved','archived') NOT NULL DEFAULT 'requested',
    assigned_to INT NULL,
    completed_at DATETIME NULL,
    metadata_json JSON NULL,
    created_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_marketing_asset_requests_uuid (uuid),
    KEY idx_marketing_asset_requests_workspace_status (workspace_id, status, due_at),
    KEY idx_marketing_asset_requests_workspace_content (workspace_id, content_item_id),
    KEY idx_marketing_asset_requests_workspace_brief (workspace_id, creative_brief_id),
    CONSTRAINT fk_marketing_asset_requests_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_marketing_asset_requests_brief FOREIGN KEY (creative_brief_id) REFERENCES marketing_creative_briefs(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_asset_requests_content FOREIGN KEY (content_item_id) REFERENCES marketing_content_items(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_asset_requests_assignee FOREIGN KEY (assigned_to) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_asset_requests_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS marketing_asset_usage (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id INT NOT NULL,
    asset_id INT NOT NULL,
    content_item_id INT NULL,
    distribution_post_id INT NULL,
    uuid CHAR(36) NOT NULL,
    usage_context VARCHAR(120) NULL,
    readiness_json JSON NULL,
    metadata_json JSON NULL,
    created_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_marketing_asset_usage_uuid (uuid),
    KEY idx_marketing_asset_usage_workspace_asset (workspace_id, asset_id),
    KEY idx_marketing_asset_usage_workspace_content (workspace_id, content_item_id),
    KEY idx_marketing_asset_usage_workspace_distribution (workspace_id, distribution_post_id),
    CONSTRAINT fk_marketing_asset_usage_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_marketing_asset_usage_asset FOREIGN KEY (asset_id) REFERENCES marketing_assets(id) ON DELETE CASCADE,
    CONSTRAINT fk_marketing_asset_usage_content FOREIGN KEY (content_item_id) REFERENCES marketing_content_items(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_asset_usage_distribution FOREIGN KEY (distribution_post_id) REFERENCES marketing_distribution_posts(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_asset_usage_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
