-- Marketing Phase 22: recurring operating rhythms and planning queues.

CREATE TABLE IF NOT EXISTS marketing_recurring_rhythms (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id INT NOT NULL,
    uuid CHAR(36) NOT NULL,
    name VARCHAR(180) NOT NULL,
    rhythm_type ENUM('campaign','content','review','report','planning') NOT NULL DEFAULT 'planning',
    cadence ENUM('weekly','biweekly','monthly','quarterly') NOT NULL DEFAULT 'weekly',
    day_of_week TINYINT NULL,
    next_run_at DATETIME NULL,
    owner_user_id INT NULL,
    checklist_json JSON NULL,
    status ENUM('active','paused','archived') NOT NULL DEFAULT 'active',
    metadata_json JSON NULL,
    created_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_marketing_rhythms_uuid (uuid),
    KEY idx_marketing_rhythms_workspace_status (workspace_id, status, next_run_at),
    KEY idx_marketing_rhythms_workspace_type (workspace_id, rhythm_type, cadence),
    CONSTRAINT fk_marketing_rhythms_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_marketing_rhythms_owner FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_rhythms_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS marketing_planning_queue_items (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id INT NOT NULL,
    rhythm_id INT NULL,
    content_item_id INT NULL,
    campaign_brief_id INT NULL,
    campaign_id INT NULL,
    uuid CHAR(36) NOT NULL,
    week_start DATE NOT NULL,
    title VARCHAR(255) NOT NULL,
    item_type ENUM('content','campaign','review','asset','report','other') NOT NULL DEFAULT 'content',
    priority ENUM('low','medium','high') NOT NULL DEFAULT 'medium',
    status ENUM('planned','in_progress','done','blocked','archived') NOT NULL DEFAULT 'planned',
    owner_user_id INT NULL,
    due_at DATETIME NULL,
    metadata_json JSON NULL,
    created_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_marketing_queue_uuid (uuid),
    KEY idx_marketing_queue_workspace_week (workspace_id, week_start, status),
    KEY idx_marketing_queue_workspace_owner (workspace_id, owner_user_id, due_at),
    KEY idx_marketing_queue_workspace_rhythm (workspace_id, rhythm_id),
    CONSTRAINT fk_marketing_queue_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_marketing_queue_rhythm FOREIGN KEY (rhythm_id) REFERENCES marketing_recurring_rhythms(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_queue_content FOREIGN KEY (content_item_id) REFERENCES marketing_content_items(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_queue_brief FOREIGN KEY (campaign_brief_id) REFERENCES marketing_campaign_briefs(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_queue_campaign FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_queue_owner FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_queue_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS marketing_checklist_templates (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id INT NOT NULL,
    uuid CHAR(36) NOT NULL,
    name VARCHAR(180) NOT NULL,
    template_type ENUM('campaign','content','review','distribution','report','other') NOT NULL DEFAULT 'content',
    checklist_json JSON NULL,
    status ENUM('active','archived') NOT NULL DEFAULT 'active',
    metadata_json JSON NULL,
    created_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_marketing_checklist_templates_uuid (uuid),
    KEY idx_marketing_checklist_templates_workspace_type (workspace_id, template_type, status),
    CONSTRAINT fk_marketing_checklist_templates_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_marketing_checklist_templates_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
