INSERT INTO marketplace_page_explainers (
    page_key,
    label,
    video_url,
    is_active
) VALUES
    ('marketing_command_center', 'Marketing Command Center page guide', NULL, 0),
    ('marketing_onboarding', 'Marketing Setup page guide', NULL, 0),
    ('marketing_content', 'Content Studio page guide', NULL, 0),
    ('marketing_context', 'Marketing Context Hub page guide', NULL, 0),
    ('marketing_admin', 'Marketing Admin Diagnostics page guide', NULL, 0),
    ('marketing_content_edit', 'Marketing Content Editor page guide', NULL, 0),
    ('marketing_content_view', 'Marketing Content Detail page guide', NULL, 0),
    ('marketing_briefs', 'Campaign Briefs page guide', NULL, 0),
    ('marketing_brief_edit', 'Campaign Brief Editor page guide', NULL, 0),
    ('marketing_brief_view', 'Campaign Brief Detail page guide', NULL, 0),
    ('marketing_calendar', 'Marketing Calendar page guide', NULL, 0),
    ('marketing_reviews', 'Marketing Approval Workbench page guide', NULL, 0),
    ('marketing_roadmap', 'Campaign Roadmap page guide', NULL, 0),
    ('marketing_persona_offer_matrix', 'Persona Offer Matrix page guide', NULL, 0),
    ('marketing_brand', 'Brand Library page guide', NULL, 0),
    ('marketing_personas', 'Personas page guide', NULL, 0),
    ('marketing_seo', 'SEO Topics page guide', NULL, 0),
    ('marketing_landing_pages', 'Landing Page Plans page guide', NULL, 0),
    ('marketing_landing_page_edit', 'Landing Page Editor page guide', NULL, 0),
    ('marketing_landing_page_view', 'Landing Page Detail page guide', NULL, 0),
    ('marketing_assets', 'Marketing Assets page guide', NULL, 0),
    ('marketing_distribution', 'Distribution Queue page guide', NULL, 0),
    ('marketing_distribution_bundle', 'Export Bundle page guide', NULL, 0),
    ('marketing_channel_exports', 'Channel Export Bundles page guide', NULL, 0),
    ('marketing_utm_links', 'UTM Links page guide', NULL, 0),
    ('marketing_email_runs', 'Marketing Email Runs page guide', NULL, 0),
    ('marketing_performance', 'Marketing Performance page guide', NULL, 0),
    ('marketing_weekly_report', 'Weekly Marketing Report page guide', NULL, 0),
    ('marketing_monthly_report', 'Monthly Marketing Report page guide', NULL, 0),
    ('marketing_assistants', 'Marketing Assistants page guide', NULL, 0),
    ('marketing_quality', 'Marketing Quality Checks page guide', NULL, 0),
    ('marketing_creative', 'Creative Production page guide', NULL, 0),
    ('marketing_operations', 'Marketing Operations page guide', NULL, 0)
ON DUPLICATE KEY UPDATE
    label = VALUES(label),
    updated_at = NOW();
