-- Marketing Phase 42: budget, spend, and ROI planning.

CREATE TABLE IF NOT EXISTS marketing_campaign_budgets (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id INT NOT NULL,
    campaign_id INT NULL,
    campaign_brief_id INT NULL,
    uuid CHAR(36) NOT NULL,
    title VARCHAR(180) NOT NULL,
    budget_period ENUM('monthly','quarterly','campaign','annual','custom') NOT NULL DEFAULT 'campaign',
    planned_budget DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    committed_budget DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    actual_spend DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    currency CHAR(3) NOT NULL DEFAULT 'USD',
    start_date DATE NULL,
    end_date DATE NULL,
    status ENUM('draft','active','closed','archived') NOT NULL DEFAULT 'draft',
    metadata_json JSON NULL,
    owner_user_id INT NULL,
    created_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_marketing_campaign_budgets_uuid (uuid),
    KEY idx_marketing_campaign_budgets_workspace_status (workspace_id, status, start_date),
    KEY idx_marketing_campaign_budgets_workspace_campaign (workspace_id, campaign_id),
    CONSTRAINT fk_marketing_campaign_budgets_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_marketing_campaign_budgets_owner FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_campaign_budgets_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS marketing_channel_spend (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id INT NOT NULL,
    budget_id INT NULL,
    campaign_id INT NULL,
    uuid CHAR(36) NOT NULL,
    channel VARCHAR(80) NOT NULL DEFAULT 'other',
    spend_date DATE NOT NULL,
    amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    currency CHAR(3) NOT NULL DEFAULT 'USD',
    vendor VARCHAR(180) NULL,
    description TEXT NULL,
    metadata_json JSON NULL,
    created_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_marketing_channel_spend_uuid (uuid),
    KEY idx_marketing_channel_spend_workspace_date (workspace_id, spend_date, channel),
    KEY idx_marketing_channel_spend_workspace_budget (workspace_id, budget_id),
    CONSTRAINT fk_marketing_channel_spend_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_marketing_channel_spend_budget FOREIGN KEY (budget_id) REFERENCES marketing_campaign_budgets(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_channel_spend_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS marketing_roi_targets (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id INT NOT NULL,
    budget_id INT NULL,
    campaign_id INT NULL,
    uuid CHAR(36) NOT NULL,
    title VARCHAR(180) NOT NULL,
    target_revenue DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    target_roi_percent DECIMAL(8,2) NULL,
    target_leads INT NOT NULL DEFAULT 0,
    target_conversions INT NOT NULL DEFAULT 0,
    attribution_model VARCHAR(80) NULL,
    status ENUM('draft','active','met','missed','archived') NOT NULL DEFAULT 'draft',
    metadata_json JSON NULL,
    created_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_marketing_roi_targets_uuid (uuid),
    KEY idx_marketing_roi_targets_workspace_status (workspace_id, status),
    KEY idx_marketing_roi_targets_workspace_budget (workspace_id, budget_id),
    CONSTRAINT fk_marketing_roi_targets_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_marketing_roi_targets_budget FOREIGN KEY (budget_id) REFERENCES marketing_campaign_budgets(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_roi_targets_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
