-- Marketing Phase 46: conversion tracking foundation.

CREATE TABLE IF NOT EXISTS marketing_visitor_sessions (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id INT NOT NULL,
    landing_page_id INT NULL,
    uuid CHAR(36) NOT NULL,
    session_key VARCHAR(80) NOT NULL,
    first_utm_source VARCHAR(120) NULL,
    first_utm_medium VARCHAR(120) NULL,
    first_utm_campaign VARCHAR(160) NULL,
    first_referrer VARCHAR(500) NULL,
    ip_hash CHAR(64) NULL,
    user_agent_hash CHAR(64) NULL,
    metadata_json JSON NULL,
    first_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_marketing_visitor_sessions_uuid (uuid),
    UNIQUE KEY uniq_marketing_visitor_sessions_workspace_key (workspace_id, session_key),
    KEY idx_marketing_visitor_sessions_workspace_landing (workspace_id, landing_page_id, last_seen_at),
    CONSTRAINT fk_marketing_visitor_sessions_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_marketing_visitor_sessions_landing FOREIGN KEY (landing_page_id) REFERENCES marketing_landing_pages(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS marketing_tracking_events (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id INT NOT NULL,
    visitor_session_id INT NULL,
    landing_page_id INT NULL,
    campaign_id INT NULL,
    content_item_id INT NULL,
    form_id INT NULL,
    utm_link_id INT NULL,
    uuid CHAR(36) NOT NULL,
    event_type ENUM('page_view','cta_click','form_start','form_submit','conversion','custom') NOT NULL DEFAULT 'custom',
    event_name VARCHAR(160) NOT NULL,
    page_url VARCHAR(700) NULL,
    referrer VARCHAR(700) NULL,
    utm_source VARCHAR(120) NULL,
    utm_medium VARCHAR(120) NULL,
    utm_campaign VARCHAR(160) NULL,
    utm_term VARCHAR(160) NULL,
    utm_content VARCHAR(160) NULL,
    metadata_json JSON NULL,
    occurred_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_marketing_tracking_events_uuid (uuid),
    KEY idx_marketing_tracking_events_workspace_type (workspace_id, event_type, occurred_at),
    KEY idx_marketing_tracking_events_workspace_landing (workspace_id, landing_page_id, occurred_at),
    KEY idx_marketing_tracking_events_workspace_campaign (workspace_id, campaign_id, occurred_at),
    KEY idx_marketing_tracking_events_workspace_session (workspace_id, visitor_session_id, occurred_at),
    CONSTRAINT fk_marketing_tracking_events_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_marketing_tracking_events_session FOREIGN KEY (visitor_session_id) REFERENCES marketing_visitor_sessions(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_tracking_events_landing FOREIGN KEY (landing_page_id) REFERENCES marketing_landing_pages(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_tracking_events_campaign FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_tracking_events_content FOREIGN KEY (content_item_id) REFERENCES marketing_content_items(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_tracking_events_form FOREIGN KEY (form_id) REFERENCES forms(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_tracking_events_utm FOREIGN KEY (utm_link_id) REFERENCES marketing_utm_links(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS marketing_landing_page_views (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id INT NOT NULL,
    landing_page_id INT NOT NULL,
    visitor_session_id INT NULL,
    tracking_event_id INT NULL,
    uuid CHAR(36) NOT NULL,
    public_token_hash CHAR(64) NULL,
    page_url VARCHAR(700) NULL,
    referrer VARCHAR(700) NULL,
    occurred_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_marketing_landing_page_views_uuid (uuid),
    KEY idx_marketing_landing_page_views_workspace_page (workspace_id, landing_page_id, occurred_at),
    KEY idx_marketing_landing_page_views_workspace_session (workspace_id, visitor_session_id, occurred_at),
    CONSTRAINT fk_marketing_landing_page_views_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_marketing_landing_page_views_landing FOREIGN KEY (landing_page_id) REFERENCES marketing_landing_pages(id) ON DELETE CASCADE,
    CONSTRAINT fk_marketing_landing_page_views_session FOREIGN KEY (visitor_session_id) REFERENCES marketing_visitor_sessions(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_landing_page_views_event FOREIGN KEY (tracking_event_id) REFERENCES marketing_tracking_events(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS marketing_cta_clicks (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id INT NOT NULL,
    landing_page_id INT NOT NULL,
    visitor_session_id INT NULL,
    tracking_event_id INT NULL,
    uuid CHAR(36) NOT NULL,
    cta_label VARCHAR(180) NULL,
    cta_destination VARCHAR(700) NULL,
    occurred_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_marketing_cta_clicks_uuid (uuid),
    KEY idx_marketing_cta_clicks_workspace_page (workspace_id, landing_page_id, occurred_at),
    KEY idx_marketing_cta_clicks_workspace_session (workspace_id, visitor_session_id, occurred_at),
    CONSTRAINT fk_marketing_cta_clicks_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_marketing_cta_clicks_landing FOREIGN KEY (landing_page_id) REFERENCES marketing_landing_pages(id) ON DELETE CASCADE,
    CONSTRAINT fk_marketing_cta_clicks_session FOREIGN KEY (visitor_session_id) REFERENCES marketing_visitor_sessions(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_cta_clicks_event FOREIGN KEY (tracking_event_id) REFERENCES marketing_tracking_events(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS marketing_conversion_events (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id INT NOT NULL,
    landing_page_id INT NULL,
    visitor_session_id INT NULL,
    tracking_event_id INT NULL,
    form_id INT NULL,
    contact_id INT NULL,
    deal_id INT NULL,
    uuid CHAR(36) NOT NULL,
    conversion_type ENUM('form_submit','lead_capture','demo_request','download','newsletter_signup','event_registration','contact_request','custom') NOT NULL DEFAULT 'lead_capture',
    conversion_value DECIMAL(12,2) NULL,
    metadata_json JSON NULL,
    occurred_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_marketing_conversion_events_uuid (uuid),
    KEY idx_marketing_conversion_events_workspace_type (workspace_id, conversion_type, occurred_at),
    KEY idx_marketing_conversion_events_workspace_landing (workspace_id, landing_page_id, occurred_at),
    KEY idx_marketing_conversion_events_workspace_contact (workspace_id, contact_id, occurred_at),
    CONSTRAINT fk_marketing_conversion_events_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_marketing_conversion_events_landing FOREIGN KEY (landing_page_id) REFERENCES marketing_landing_pages(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_conversion_events_session FOREIGN KEY (visitor_session_id) REFERENCES marketing_visitor_sessions(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_conversion_events_event FOREIGN KEY (tracking_event_id) REFERENCES marketing_tracking_events(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_conversion_events_form FOREIGN KEY (form_id) REFERENCES forms(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_conversion_events_contact FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_conversion_events_deal FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
