-- Marketing Phase 47: attribution pipeline upgrade.

CREATE TABLE IF NOT EXISTS marketing_attribution_touchpoints (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id INT NOT NULL,
    uuid CHAR(36) NOT NULL,
    visitor_session_id INT NULL,
    tracking_event_id INT NULL,
    landing_page_id INT NULL,
    campaign_id INT NULL,
    content_item_id INT NULL,
    form_id INT NULL,
    utm_link_id INT NULL,
    contact_id INT NULL,
    deal_id INT NULL,
    touchpoint_type ENUM('first_touch','last_touch','assist','conversion','revenue') NOT NULL DEFAULT 'assist',
    attribution_model ENUM('first_touch','last_touch','linear','manual') NOT NULL DEFAULT 'linear',
    source VARCHAR(120) NULL,
    medium VARCHAR(120) NULL,
    campaign_name VARCHAR(160) NULL,
    channel VARCHAR(80) NULL,
    touchpoint_weight DECIMAL(8,4) NOT NULL DEFAULT 1.0000,
    revenue_amount DECIMAL(12,2) NULL,
    metadata_json JSON NULL,
    occurred_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_marketing_attribution_touchpoints_uuid (uuid),
    KEY idx_marketing_attr_touchpoints_workspace_type (workspace_id, touchpoint_type, occurred_at),
    KEY idx_marketing_attr_touchpoints_workspace_session (workspace_id, visitor_session_id, occurred_at),
    KEY idx_marketing_attr_touchpoints_workspace_campaign (workspace_id, campaign_id, occurred_at),
    KEY idx_marketing_attr_touchpoints_workspace_content (workspace_id, content_item_id, occurred_at),
    KEY idx_marketing_attr_touchpoints_workspace_contact (workspace_id, contact_id, occurred_at),
    KEY idx_marketing_attr_touchpoints_workspace_deal (workspace_id, deal_id, occurred_at),
    KEY idx_marketing_attr_touchpoints_workspace_source (workspace_id, source, medium, occurred_at),
    CONSTRAINT fk_marketing_attr_touchpoints_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_marketing_attr_touchpoints_session FOREIGN KEY (visitor_session_id) REFERENCES marketing_visitor_sessions(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_attr_touchpoints_event FOREIGN KEY (tracking_event_id) REFERENCES marketing_tracking_events(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_attr_touchpoints_landing FOREIGN KEY (landing_page_id) REFERENCES marketing_landing_pages(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_attr_touchpoints_campaign FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_attr_touchpoints_content FOREIGN KEY (content_item_id) REFERENCES marketing_content_items(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_attr_touchpoints_form FOREIGN KEY (form_id) REFERENCES forms(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_attr_touchpoints_utm FOREIGN KEY (utm_link_id) REFERENCES marketing_utm_links(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_attr_touchpoints_contact FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_attr_touchpoints_deal FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS marketing_attribution_summaries (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id INT NOT NULL,
    uuid CHAR(36) NOT NULL,
    summary_type ENUM('weekly','monthly','campaign','content','source','custom') NOT NULL DEFAULT 'monthly',
    period_start DATE NULL,
    period_end DATE NULL,
    payload_json JSON NULL,
    metadata_json JSON NULL,
    created_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_marketing_attribution_summaries_uuid (uuid),
    KEY idx_marketing_attribution_summaries_workspace_type (workspace_id, summary_type, period_start, period_end),
    CONSTRAINT fk_marketing_attribution_summaries_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_marketing_attribution_summaries_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
