-- Marketing Phase 49: lead capture to sales handoff.

CREATE TABLE IF NOT EXISTS marketing_handoff_rules (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id INT NOT NULL,
    uuid CHAR(36) NOT NULL,
    name VARCHAR(180) NOT NULL,
    status ENUM('draft','active','paused','archived') NOT NULL DEFAULT 'draft',
    priority ENUM('low','medium','high','urgent') NOT NULL DEFAULT 'high',
    source_type ENUM('any','landing_page','form','campaign','conversion_goal','manual') NOT NULL DEFAULT 'any',
    landing_page_id INT NULL,
    form_id INT NULL,
    campaign_id INT NULL,
    conversion_goal_id INT NULL,
    assigned_to INT NULL,
    sla_minutes INT NOT NULL DEFAULT 1440,
    task_title_template VARCHAR(255) NULL,
    metadata_json JSON NULL,
    created_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_marketing_handoff_rules_uuid (uuid),
    KEY idx_marketing_handoff_rules_workspace_status (workspace_id, status, updated_at),
    KEY idx_marketing_handoff_rules_workspace_source (workspace_id, source_type, status),
    CONSTRAINT fk_marketing_handoff_rules_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_marketing_handoff_rules_landing FOREIGN KEY (landing_page_id) REFERENCES marketing_landing_pages(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_handoff_rules_form FOREIGN KEY (form_id) REFERENCES forms(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_handoff_rules_campaign FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_handoff_rules_goal FOREIGN KEY (conversion_goal_id) REFERENCES marketing_conversion_goals(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_handoff_rules_assignee FOREIGN KEY (assigned_to) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_handoff_rules_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS marketing_lead_handoffs (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id INT NOT NULL,
    uuid CHAR(36) NOT NULL,
    conversion_event_id INT NULL,
    tracking_event_id INT NULL,
    visitor_session_id INT NULL,
    landing_page_id INT NULL,
    campaign_id INT NULL,
    content_item_id INT NULL,
    form_id INT NULL,
    conversion_goal_id INT NULL,
    contact_id INT NULL,
    deal_id INT NULL,
    handoff_rule_id INT NULL,
    task_id INT NULL,
    status ENUM('new','assigned','contacted','qualified','rejected','converted','archived') NOT NULL DEFAULT 'new',
    priority ENUM('low','medium','high','urgent') NOT NULL DEFAULT 'high',
    assigned_to INT NULL,
    source VARCHAR(120) NULL,
    handoff_note TEXT NULL,
    rejection_reason TEXT NULL,
    sla_due_at DATETIME NULL,
    assigned_at DATETIME NULL,
    first_contacted_at DATETIME NULL,
    qualified_at DATETIME NULL,
    rejected_at DATETIME NULL,
    converted_at DATETIME NULL,
    metadata_json JSON NULL,
    created_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_marketing_lead_handoffs_uuid (uuid),
    UNIQUE KEY uniq_marketing_lead_handoffs_conversion (workspace_id, conversion_event_id),
    KEY idx_marketing_handoffs_workspace_status (workspace_id, status, sla_due_at),
    KEY idx_marketing_handoffs_workspace_assignee (workspace_id, assigned_to, status),
    KEY idx_marketing_handoffs_workspace_contact (workspace_id, contact_id, created_at),
    KEY idx_marketing_handoffs_workspace_campaign (workspace_id, campaign_id, created_at),
    CONSTRAINT fk_marketing_handoffs_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_marketing_handoffs_conversion FOREIGN KEY (conversion_event_id) REFERENCES marketing_conversion_events(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_handoffs_tracking FOREIGN KEY (tracking_event_id) REFERENCES marketing_tracking_events(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_handoffs_session FOREIGN KEY (visitor_session_id) REFERENCES marketing_visitor_sessions(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_handoffs_landing FOREIGN KEY (landing_page_id) REFERENCES marketing_landing_pages(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_handoffs_campaign FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_handoffs_content FOREIGN KEY (content_item_id) REFERENCES marketing_content_items(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_handoffs_form FOREIGN KEY (form_id) REFERENCES forms(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_handoffs_goal FOREIGN KEY (conversion_goal_id) REFERENCES marketing_conversion_goals(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_handoffs_contact FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_handoffs_deal FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_handoffs_rule FOREIGN KEY (handoff_rule_id) REFERENCES marketing_handoff_rules(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_handoffs_task FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_handoffs_assignee FOREIGN KEY (assigned_to) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_handoffs_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO marketplace_page_explainers (
    page_key,
    label,
    video_url,
    is_active
) VALUES
    ('marketing_handoffs', 'Lead Handoffs page guide', NULL, 0)
ON DUPLICATE KEY UPDATE
    label = VALUES(label),
    updated_at = NOW();
