-- Marketing Phase 89: reusable marketing template and brand execution system.

CREATE TABLE IF NOT EXISTS marketing_reusable_templates (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id INT NOT NULL,
    uuid CHAR(36) NOT NULL,
    template_key VARCHAR(120) NULL,
    name VARCHAR(190) NOT NULL,
    template_type ENUM('content','landing_page','email','ad','social','brief','distribution','other') NOT NULL DEFAULT 'content',
    channel VARCHAR(80) NULL,
    content_type VARCHAR(80) NULL,
    status ENUM('active','draft','archived') NOT NULL DEFAULT 'active',
    title_pattern VARCHAR(255) NULL,
    objective TEXT NULL,
    body_template MEDIUMTEXT NULL,
    cta_template TEXT NULL,
    media_notes TEXT NULL,
    checklist_json JSON NULL,
    variables_json JSON NULL,
    brand_profile_id INT NULL,
    persona_id INT NULL,
    offer_context_item_id INT NULL,
    email_template_id INT NULL,
    usage_count INT NOT NULL DEFAULT 0,
    last_used_at DATETIME NULL,
    metadata_json JSON NULL,
    owner_user_id INT NULL,
    created_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_marketing_reusable_templates_uuid (uuid),
    UNIQUE KEY uniq_marketing_reusable_templates_workspace_key (workspace_id, template_key),
    KEY idx_marketing_reusable_templates_workspace_type (workspace_id, template_type, status),
    KEY idx_marketing_reusable_templates_workspace_channel (workspace_id, channel, status),
    KEY idx_marketing_reusable_templates_workspace_brand (workspace_id, brand_profile_id),
    KEY idx_marketing_reusable_templates_workspace_persona (workspace_id, persona_id),
    KEY idx_marketing_reusable_templates_workspace_owner (workspace_id, owner_user_id),
    CONSTRAINT fk_marketing_reusable_templates_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_marketing_reusable_templates_brand FOREIGN KEY (brand_profile_id) REFERENCES marketing_brand_profiles(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_reusable_templates_persona FOREIGN KEY (persona_id) REFERENCES marketing_personas(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_reusable_templates_offer FOREIGN KEY (offer_context_item_id) REFERENCES marketing_context_items(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_reusable_templates_owner FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_reusable_templates_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

