-- Marketing Phase 93: campaign-level creative requirements and readiness.

CREATE TABLE IF NOT EXISTS marketing_campaign_creative_requirements (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id INT NOT NULL,
    campaign_id INT NOT NULL,
    uuid CHAR(36) NOT NULL,
    title VARCHAR(190) NOT NULL,
    requirement_type ENUM('image','video','logo','thumbnail','banner','document','ad_creative','landing_visual','social_asset','email_banner','other') NOT NULL DEFAULT 'image',
    channel VARCHAR(80) NULL,
    placement VARCHAR(120) NULL,
    priority ENUM('low','normal','high','urgent') NOT NULL DEFAULT 'normal',
    status ENUM('planned','requested','in_progress','ready','blocked','waived','archived') NOT NULL DEFAULT 'planned',
    required_count INT NOT NULL DEFAULT 1,
    creative_brief_id INT NULL,
    asset_request_id INT NULL,
    media_file_id INT NULL,
    content_item_id INT NULL,
    landing_page_id INT NULL,
    channel_export_bundle_id INT NULL,
    due_at DATETIME NULL,
    notes TEXT NULL,
    readiness_json JSON NULL,
    metadata_json JSON NULL,
    owner_user_id INT NULL,
    created_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_marketing_campaign_creative_req_uuid (uuid),
    KEY idx_marketing_campaign_creative_req_workspace_status (workspace_id, status, priority),
    KEY idx_marketing_campaign_creative_req_workspace_campaign (workspace_id, campaign_id, status),
    KEY idx_marketing_campaign_creative_req_workspace_media (workspace_id, media_file_id),
    KEY idx_marketing_campaign_creative_req_workspace_owner (workspace_id, owner_user_id, status),
    CONSTRAINT fk_marketing_campaign_creative_req_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_marketing_campaign_creative_req_campaign FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE,
    CONSTRAINT fk_marketing_campaign_creative_req_brief FOREIGN KEY (creative_brief_id) REFERENCES marketing_creative_briefs(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_campaign_creative_req_asset_request FOREIGN KEY (asset_request_id) REFERENCES marketing_asset_requests(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_campaign_creative_req_media FOREIGN KEY (media_file_id) REFERENCES marketing_media_files(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_campaign_creative_req_content FOREIGN KEY (content_item_id) REFERENCES marketing_content_items(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_campaign_creative_req_landing FOREIGN KEY (landing_page_id) REFERENCES marketing_landing_pages(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_campaign_creative_req_channel_bundle FOREIGN KEY (channel_export_bundle_id) REFERENCES marketing_channel_export_bundles(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_campaign_creative_req_owner FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_campaign_creative_req_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
