-- Marketing Phase 45: CRM lifecycle insight snapshots for context-aware Marketing integration.

CREATE TABLE IF NOT EXISTS marketing_crm_lifecycle_insights (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id INT NOT NULL,
    uuid CHAR(36) NOT NULL,
    insight_scope ENUM('workspace','contact','company','deal','campaign','form','task') NOT NULL DEFAULT 'workspace',
    status ENUM('current','stale','archived') NOT NULL DEFAULT 'current',
    readiness_status ENUM('ready','attention','missing','blocked') NOT NULL DEFAULT 'attention',
    lifecycle_score INT NOT NULL DEFAULT 0,
    contact_id INT NULL,
    company_id INT NULL,
    deal_id INT NULL,
    campaign_id INT NULL,
    form_id INT NULL,
    task_id INT NULL,
    counts_json JSON NULL,
    recommendations_json JSON NULL,
    linked_records_json JSON NULL,
    metadata_json JSON NULL,
    generated_by INT NULL,
    generated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_marketing_crm_lifecycle_insights_uuid (uuid),
    KEY idx_marketing_crm_lifecycle_workspace_scope (workspace_id, insight_scope, status, generated_at),
    KEY idx_marketing_crm_lifecycle_workspace_contact (workspace_id, contact_id, status),
    KEY idx_marketing_crm_lifecycle_workspace_company (workspace_id, company_id, status),
    KEY idx_marketing_crm_lifecycle_workspace_deal (workspace_id, deal_id, status),
    KEY idx_marketing_crm_lifecycle_workspace_campaign (workspace_id, campaign_id, status),
    KEY idx_marketing_crm_lifecycle_workspace_form (workspace_id, form_id, status),
    CONSTRAINT fk_marketing_crm_lifecycle_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_marketing_crm_lifecycle_contact FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_crm_lifecycle_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_crm_lifecycle_deal FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_crm_lifecycle_campaign FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_crm_lifecycle_form FOREIGN KEY (form_id) REFERENCES forms(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_crm_lifecycle_task FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_crm_lifecycle_generator FOREIGN KEY (generated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
