-- Marketing Phase 53: media production workflow queue.

CREATE TABLE IF NOT EXISTS marketing_media_production_work_items (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id INT NOT NULL,
    uuid CHAR(36) NOT NULL,
    title VARCHAR(190) NOT NULL,
    work_type ENUM('design','video_edit','copy_adaptation','thumbnail','landing_visual','social_pack','email_banner','ad_creative','asset_cleanup','quality_review','other') NOT NULL DEFAULT 'design',
    status ENUM('requested','assigned','in_progress','review','ready','approved','blocked','archived') NOT NULL DEFAULT 'requested',
    priority ENUM('low','normal','high','urgent') NOT NULL DEFAULT 'normal',
    campaign_id INT NULL,
    content_item_id INT NULL,
    landing_page_id INT NULL,
    distribution_post_id INT NULL,
    channel_export_bundle_id INT NULL,
    creative_brief_id INT NULL,
    asset_request_id INT NULL,
    campaign_creative_requirement_id INT NULL,
    media_file_id INT NULL,
    channel VARCHAR(80) NULL,
    placement VARCHAR(120) NULL,
    requested_format VARCHAR(160) NULL,
    dimensions VARCHAR(120) NULL,
    due_at DATETIME NULL,
    started_at DATETIME NULL,
    completed_at DATETIME NULL,
    assigned_to INT NULL,
    owner_user_id INT NULL,
    blocked_reason TEXT NULL,
    production_notes TEXT NULL,
    checklist_json JSON NULL,
    readiness_json JSON NULL,
    metadata_json JSON NULL,
    created_by INT NULL,
    archived_at DATETIME NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_marketing_media_production_work_uuid (uuid),
    KEY idx_marketing_media_production_workspace_status (workspace_id, status, priority, due_at),
    KEY idx_marketing_media_production_workspace_campaign (workspace_id, campaign_id, status),
    KEY idx_marketing_media_production_workspace_assignee (workspace_id, assigned_to, status),
    KEY idx_marketing_media_production_workspace_media (workspace_id, media_file_id, status),
    KEY idx_marketing_media_production_workspace_content (workspace_id, content_item_id, status),
    CONSTRAINT fk_marketing_media_production_work_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_marketing_media_production_work_campaign FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_media_production_work_content FOREIGN KEY (content_item_id) REFERENCES marketing_content_items(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_media_production_work_landing FOREIGN KEY (landing_page_id) REFERENCES marketing_landing_pages(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_media_production_work_distribution FOREIGN KEY (distribution_post_id) REFERENCES marketing_distribution_posts(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_media_production_work_bundle FOREIGN KEY (channel_export_bundle_id) REFERENCES marketing_channel_export_bundles(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_media_production_work_brief FOREIGN KEY (creative_brief_id) REFERENCES marketing_creative_briefs(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_media_production_work_asset_request FOREIGN KEY (asset_request_id) REFERENCES marketing_asset_requests(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_media_production_work_requirement FOREIGN KEY (campaign_creative_requirement_id) REFERENCES marketing_campaign_creative_requirements(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_media_production_work_media FOREIGN KEY (media_file_id) REFERENCES marketing_media_files(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_media_production_work_assignee FOREIGN KEY (assigned_to) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_media_production_work_owner FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_media_production_work_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
