-- Marketing live execution: dry-run rehearsal and promotion evidence.
-- Rehearsals keep live queue promotion explicit and auditable without sending
-- anything externally during the dry-run step.

CREATE TABLE IF NOT EXISTS marketing_live_rehearsal_runs (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id INT NOT NULL,
    uuid CHAR(36) NOT NULL,
    source_type ENUM('content','channel_export_bundle','distribution_post','execution_queue','other') NOT NULL DEFAULT 'other',
    status ENUM('draft','dry_run_passed','dry_run_failed','pending_approval','approved','rejected','promoted','cancelled','blocked') NOT NULL DEFAULT 'draft',
    content_item_id INT NULL,
    distribution_post_id INT NULL,
    channel_export_bundle_id INT NULL,
    source_queue_id INT NULL,
    promoted_queue_id INT NULL,
    dry_run_queue_id INT NULL,
    dry_run_attempt_id INT NULL,
    connector_id INT NULL,
    execution_type ENUM('email','whatsapp','sms','social','ad','website_webhook','other') NOT NULL DEFAULT 'other',
    target_channel VARCHAR(80) NULL,
    target_recipient VARCHAR(255) NULL,
    checklist_json JSON NULL,
    dry_run_evidence_json JSON NULL,
    approval_json JSON NULL,
    manager_override_json JSON NULL,
    metadata_json JSON NULL,
    requested_by INT NULL,
    approved_by INT NULL,
    approved_at DATETIME NULL,
    promoted_by INT NULL,
    promoted_at DATETIME NULL,
    created_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_marketing_live_rehearsal_uuid (uuid),
    KEY idx_marketing_live_rehearsal_workspace_status (workspace_id, status, updated_at),
    KEY idx_marketing_live_rehearsal_workspace_source (workspace_id, source_type, content_item_id, channel_export_bundle_id),
    KEY idx_marketing_live_rehearsal_workspace_connector (workspace_id, connector_id, status),
    KEY idx_marketing_live_rehearsal_workspace_queue (workspace_id, promoted_queue_id, dry_run_queue_id),
    CONSTRAINT fk_marketing_live_rehearsal_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_marketing_live_rehearsal_content FOREIGN KEY (content_item_id) REFERENCES marketing_content_items(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_live_rehearsal_distribution FOREIGN KEY (distribution_post_id) REFERENCES marketing_distribution_posts(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_live_rehearsal_bundle FOREIGN KEY (channel_export_bundle_id) REFERENCES marketing_channel_export_bundles(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_live_rehearsal_source_queue FOREIGN KEY (source_queue_id) REFERENCES marketing_execution_queue(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_live_rehearsal_promoted_queue FOREIGN KEY (promoted_queue_id) REFERENCES marketing_execution_queue(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_live_rehearsal_dry_queue FOREIGN KEY (dry_run_queue_id) REFERENCES marketing_execution_queue(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_live_rehearsal_dry_attempt FOREIGN KEY (dry_run_attempt_id) REFERENCES marketing_execution_attempts(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_live_rehearsal_connector FOREIGN KEY (connector_id) REFERENCES marketing_channel_connectors(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_live_rehearsal_requested_by FOREIGN KEY (requested_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_live_rehearsal_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_live_rehearsal_promoted_by FOREIGN KEY (promoted_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_live_rehearsal_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE marketing_execution_queue
    ADD COLUMN IF NOT EXISTS live_rehearsal_run_id INT NULL AFTER connector_id,
    ADD COLUMN IF NOT EXISTS live_rehearsal_required TINYINT(1) NOT NULL DEFAULT 0 AFTER live_rehearsal_run_id,
    ADD COLUMN IF NOT EXISTS live_rehearsal_status VARCHAR(40) NULL AFTER live_rehearsal_required,
    ADD COLUMN IF NOT EXISTS live_rehearsal_evidence_json JSON NULL AFTER live_rehearsal_status,
    ADD COLUMN IF NOT EXISTS live_manager_override_json JSON NULL AFTER live_rehearsal_evidence_json,
    ADD INDEX IF NOT EXISTS idx_marketing_execution_queue_rehearsal (workspace_id, live_rehearsal_run_id, live_rehearsal_status);
