CREATE TABLE IF NOT EXISTS guided_demo_sessions (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    session_uuid CHAR(36) NOT NULL,
    workspace_id INT NOT NULL,
    user_id INT NOT NULL,
    demo_run_id INT NULL,
    seed_profile VARCHAR(80) NOT NULL DEFAULT 'solo_founder_launch',
    status ENUM('pending', 'active', 'completed', 'exited', 'cleanup_failed') NOT NULL DEFAULT 'pending',
    current_step_key VARCHAR(80) NOT NULL DEFAULT 'dashboard_overview',
    cleanup_status ENUM('not_started', 'pending', 'succeeded', 'failed') NOT NULL DEFAULT 'not_started',
    cleanup_summary_json JSON NULL,
    metadata_json JSON NULL,
    started_at DATETIME NULL,
    completed_at DATETIME NULL,
    exited_at DATETIME NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_guided_demo_sessions_uuid (session_uuid),
    KEY idx_guided_demo_sessions_workspace_status (workspace_id, status),
    KEY idx_guided_demo_sessions_user_status (user_id, status),
    KEY idx_guided_demo_sessions_run (demo_run_id),
    CONSTRAINT fk_guided_demo_sessions_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_guided_demo_sessions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_guided_demo_sessions_run FOREIGN KEY (demo_run_id) REFERENCES demo_runs(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS guided_demo_plugin_installs (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    session_id BIGINT NOT NULL,
    workspace_id INT NOT NULL,
    skill_key VARCHAR(80) NOT NULL,
    install_id INT NULL,
    was_preexisting TINYINT(1) NOT NULL DEFAULT 0,
    previous_status VARCHAR(40) NULL,
    previous_config_json JSON NULL,
    restored_at DATETIME NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_guided_demo_plugin_installs_session_skill (session_id, skill_key),
    KEY idx_guided_demo_plugin_installs_workspace (workspace_id),
    KEY idx_guided_demo_plugin_installs_install (install_id),
    CONSTRAINT fk_guided_demo_plugin_installs_session FOREIGN KEY (session_id) REFERENCES guided_demo_sessions(id) ON DELETE CASCADE,
    CONSTRAINT fk_guided_demo_plugin_installs_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_guided_demo_plugin_installs_install FOREIGN KEY (install_id) REFERENCES workspace_skill_installs(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS guided_demo_events (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    session_id BIGINT NOT NULL,
    workspace_id INT NOT NULL,
    user_id INT NULL,
    step_key VARCHAR(80) NULL,
    event_type ENUM('created', 'started', 'shown', 'advanced', 'back', 'skipped', 'exited', 'completed', 'cleanup_started', 'cleanup_succeeded', 'cleanup_failed', 'fallback_target') NOT NULL,
    page VARCHAR(160) NULL,
    metadata_json JSON NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    KEY idx_guided_demo_events_session (session_id, created_at),
    KEY idx_guided_demo_events_workspace (workspace_id, created_at),
    KEY idx_guided_demo_events_type (event_type),
    CONSTRAINT fk_guided_demo_events_session FOREIGN KEY (session_id) REFERENCES guided_demo_sessions(id) ON DELETE CASCADE,
    CONSTRAINT fk_guided_demo_events_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_guided_demo_events_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS guided_demo_package_intents (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    workspace_id INT NOT NULL,
    user_id INT NOT NULL,
    session_id BIGINT NULL,
    package_code ENUM('sprint', 'launch', 'operator') NOT NULL,
    status ENUM('requested', 'checkout_started', 'completed', 'cancelled') NOT NULL DEFAULT 'requested',
    contact_method VARCHAR(40) NULL,
    notes TEXT NULL,
    metadata_json JSON NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_guided_demo_package_intents_workspace (workspace_id, created_at),
    KEY idx_guided_demo_package_intents_user (user_id, created_at),
    KEY idx_guided_demo_package_intents_session (session_id),
    KEY idx_guided_demo_package_intents_package_status (package_code, status),
    CONSTRAINT fk_guided_demo_package_intents_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_guided_demo_package_intents_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_guided_demo_package_intents_session FOREIGN KEY (session_id) REFERENCES guided_demo_sessions(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
