CREATE TABLE IF NOT EXISTS billing_invoices (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    document_key VARCHAR(191) NOT NULL,
    document_number VARCHAR(60) NOT NULL,
    workspace_id INT NOT NULL,
    subscription_id INT NOT NULL,
    billing_plan_price_id INT NOT NULL,
    billing_transaction_id BIGINT NULL,
    checkout_session_id BIGINT NULL,
    negotiated_offer_id BIGINT UNSIGNED NULL,
    provider VARCHAR(50) NULL,
    provider_reference VARCHAR(120) NULL,
    provider_subscription_code VARCHAR(120) NULL,
    provider_customer_code VARCHAR(120) NULL,
    package_code VARCHAR(100) NOT NULL,
    package_name VARCHAR(191) NOT NULL,
    buyer_workspace_name VARCHAR(191) NULL,
    buyer_workspace_slug VARCHAR(191) NULL,
    buyer_user_id INT NULL,
    buyer_email VARCHAR(191) NULL,
    seller_legal_name VARCHAR(191) NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'KES',
    amount DECIMAL(14,2) NOT NULL DEFAULT 0,
    tax_total DECIMAL(14,2) NOT NULL DEFAULT 0,
    grand_total DECIMAL(14,2) NOT NULL DEFAULT 0,
    period_start DATETIME NULL,
    period_end DATETIME NULL,
    line_items_json JSON NULL,
    metadata_json JSON NULL,
    issued_at DATETIME NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_billing_invoices_document_key (document_key),
    UNIQUE KEY uniq_billing_invoices_document_number (document_number),
    KEY idx_billing_invoices_workspace (workspace_id, issued_at),
    KEY idx_billing_invoices_subscription (subscription_id, issued_at),
    KEY idx_billing_invoices_transaction (billing_transaction_id),
    KEY idx_billing_invoices_checkout (checkout_session_id),
    KEY idx_billing_invoices_price (billing_plan_price_id),
    KEY idx_billing_invoices_offer (negotiated_offer_id),
    CONSTRAINT fk_billing_invoices_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_billing_invoices_subscription FOREIGN KEY (subscription_id) REFERENCES workspace_subscriptions(id) ON DELETE CASCADE,
    CONSTRAINT fk_billing_invoices_price FOREIGN KEY (billing_plan_price_id) REFERENCES billing_plan_prices(id) ON DELETE RESTRICT,
    CONSTRAINT fk_billing_invoices_transaction FOREIGN KEY (billing_transaction_id) REFERENCES billing_transactions(id) ON DELETE SET NULL,
    CONSTRAINT fk_billing_invoices_checkout FOREIGN KEY (checkout_session_id) REFERENCES billing_checkout_sessions(id) ON DELETE SET NULL,
    CONSTRAINT fk_billing_invoices_offer FOREIGN KEY (negotiated_offer_id) REFERENCES workspace_negotiated_package_offers(id) ON DELETE SET NULL,
    CONSTRAINT fk_billing_invoices_buyer_user FOREIGN KEY (buyer_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
