-- Production Social Media plugin runtime.
-- All records are workspace-scoped and remain inaccessible unless the
-- Marketplace Social Media plugin is installed for that workspace.

CREATE TABLE IF NOT EXISTS social_media_settings (
    workspace_id INT PRIMARY KEY,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    approval_required TINYINT(1) NOT NULL DEFAULT 1,
    timezone VARCHAR(80) NOT NULL DEFAULT 'Africa/Nairobi',
    brand_name VARCHAR(180) NULL,
    brand_voice TEXT NULL,
    target_audience TEXT NULL,
    products_services TEXT NULL,
    approved_claims TEXT NULL,
    prohibited_claims TEXT NULL,
    preferred_cta TEXT NULL,
    default_utm_source VARCHAR(120) NOT NULL DEFAULT 'social',
    default_utm_medium VARCHAR(120) NOT NULL DEFAULT 'organic_social',
    metrics_sync_enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_by INT NULL,
    updated_by INT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_social_media_settings_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_social_media_settings_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_social_media_settings_updater FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS social_media_accounts (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id INT NOT NULL,
    uuid CHAR(36) NOT NULL,
    provider ENUM('meta','linkedin') NOT NULL,
    channel ENUM('facebook','instagram','linkedin') NOT NULL,
    external_account_id VARCHAR(255) NOT NULL,
    parent_account_id VARCHAR(255) NULL,
    account_name VARCHAR(255) NOT NULL,
    account_handle VARCHAR(255) NULL,
    status ENUM('pending','active','expired','revoked','error','disconnected') NOT NULL DEFAULT 'pending',
    scopes_json JSON NULL,
    access_token_encrypted MEDIUMTEXT NOT NULL,
    refresh_token_encrypted MEDIUMTEXT NULL,
    token_expires_at DATETIME NULL,
    last_verified_at DATETIME NULL,
    last_metrics_sync_at DATETIME NULL,
    last_error TEXT NULL,
    metadata_json JSON NULL,
    connected_by INT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_social_media_account_uuid (uuid),
    UNIQUE KEY uniq_social_media_workspace_account (workspace_id, channel, external_account_id),
    KEY idx_social_media_account_status (workspace_id, status, channel),
    KEY idx_social_media_account_expiry (status, token_expires_at),
    CONSTRAINT fk_social_media_account_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_social_media_account_user FOREIGN KEY (connected_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS social_media_oauth_states (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id INT NOT NULL,
    provider ENUM('meta','linkedin') NOT NULL,
    state_hash CHAR(64) NOT NULL,
    requested_by INT NOT NULL,
    return_path VARCHAR(500) NULL,
    expires_at DATETIME NOT NULL,
    consumed_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_social_media_oauth_state (state_hash),
    KEY idx_social_media_oauth_expiry (provider, expires_at, consumed_at),
    CONSTRAINT fk_social_media_oauth_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_social_media_oauth_user FOREIGN KEY (requested_by) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS social_media_publish_jobs (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id INT NOT NULL,
    uuid CHAR(36) NOT NULL,
    account_id INT NOT NULL,
    content_item_id INT NULL,
    distribution_post_id INT NULL,
    campaign_id INT NULL,
    status ENUM('draft','pending_approval','approved','queued','processing','published','failed','cancelled') NOT NULL DEFAULT 'draft',
    caption TEXT NOT NULL,
    link_url VARCHAR(1000) NULL,
    media_json JSON NULL,
    scheduled_at DATETIME NULL,
    approved_by INT NULL,
    approved_at DATETIME NULL,
    provider_post_id VARCHAR(255) NULL,
    provider_url VARCHAR(1000) NULL,
    attempts INT NOT NULL DEFAULT 0,
    max_attempts INT NOT NULL DEFAULT 5,
    next_attempt_at DATETIME NULL,
    idempotency_key CHAR(64) NOT NULL,
    request_json JSON NULL,
    response_json JSON NULL,
    error_class VARCHAR(100) NULL,
    error_message TEXT NULL,
    published_at DATETIME NULL,
    created_by INT NULL,
    updated_by INT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_social_media_job_uuid (uuid),
    UNIQUE KEY uniq_social_media_job_idempotency (workspace_id, idempotency_key),
    KEY idx_social_media_job_due (status, scheduled_at, next_attempt_at),
    KEY idx_social_media_job_workspace_status (workspace_id, status, scheduled_at),
    KEY idx_social_media_job_account (workspace_id, account_id, created_at),
    CONSTRAINT fk_social_media_job_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_social_media_job_account FOREIGN KEY (account_id) REFERENCES social_media_accounts(id) ON DELETE CASCADE,
    CONSTRAINT fk_social_media_job_content FOREIGN KEY (content_item_id) REFERENCES marketing_content_items(id) ON DELETE SET NULL,
    CONSTRAINT fk_social_media_job_distribution FOREIGN KEY (distribution_post_id) REFERENCES marketing_distribution_posts(id) ON DELETE SET NULL,
    CONSTRAINT fk_social_media_job_campaign FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE SET NULL,
    CONSTRAINT fk_social_media_job_approver FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_social_media_job_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_social_media_job_updater FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS social_media_metric_snapshots (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id INT NOT NULL,
    account_id INT NOT NULL,
    publish_job_id INT NULL,
    provider_post_id VARCHAR(255) NOT NULL,
    impressions BIGINT NOT NULL DEFAULT 0,
    reach BIGINT NOT NULL DEFAULT 0,
    engagements BIGINT NOT NULL DEFAULT 0,
    likes BIGINT NOT NULL DEFAULT 0,
    comments BIGINT NOT NULL DEFAULT 0,
    shares BIGINT NOT NULL DEFAULT 0,
    clicks BIGINT NOT NULL DEFAULT 0,
    video_views BIGINT NOT NULL DEFAULT 0,
    followers BIGINT NOT NULL DEFAULT 0,
    raw_json JSON NULL,
    captured_at DATETIME NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_social_media_metric_capture (account_id, provider_post_id, captured_at),
    KEY idx_social_media_metric_workspace (workspace_id, captured_at),
    KEY idx_social_media_metric_job (publish_job_id, captured_at),
    CONSTRAINT fk_social_media_metric_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_social_media_metric_account FOREIGN KEY (account_id) REFERENCES social_media_accounts(id) ON DELETE CASCADE,
    CONSTRAINT fk_social_media_metric_job FOREIGN KEY (publish_job_id) REFERENCES social_media_publish_jobs(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS social_media_events (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id INT NOT NULL,
    event_type ENUM('settings_saved','oauth_started','account_connected','account_verified','account_disconnected','job_created','job_approved','job_cancelled','publish_started','publish_succeeded','publish_failed','metrics_synced') NOT NULL,
    status ENUM('info','success','warning','failed') NOT NULL DEFAULT 'info',
    subject_type ENUM('workspace','account','publish_job') NOT NULL DEFAULT 'workspace',
    subject_id INT NULL,
    message VARCHAR(500) NOT NULL,
    metadata_json JSON NULL,
    actor_user_id INT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_social_media_events_workspace (workspace_id, created_at),
    KEY idx_social_media_events_subject (workspace_id, subject_type, subject_id, created_at),
    CONSTRAINT fk_social_media_event_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_social_media_event_user FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
