-- Coordinated, review-first campaign generation ledger.

CREATE TABLE IF NOT EXISTS marketing_generation_runs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    workspace_id INT NOT NULL,
    uuid CHAR(36) NOT NULL,
    run_type VARCHAR(40) NOT NULL DEFAULT 'campaign_kit',
    status ENUM('draft','generating','ready','partially_accepted','accepted','failed','archived') NOT NULL DEFAULT 'draft',
    title VARCHAR(255) NOT NULL,
    objective TEXT NULL,
    target_audience TEXT NULL,
    offer_text TEXT NULL,
    cta_text VARCHAR(500) NULL,
    funnel_stage VARCHAR(80) NULL,
    campaign_id INT NULL,
    campaign_brief_id INT NULL,
    brand_profile_id INT NULL,
    persona_id INT NULL,
    audience_segment_id INT NULL,
    channels_json JSON NULL,
    message_house_json JSON NULL,
    context_json JSON NULL,
    provider_json JSON NULL,
    quality_json JSON NULL,
    error_text TEXT NULL,
    generated_at DATETIME NULL,
    created_by INT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_marketing_generation_run_uuid (workspace_id, uuid),
    KEY idx_marketing_generation_run_status (workspace_id, status, updated_at),
    KEY idx_marketing_generation_run_campaign (workspace_id, campaign_id, updated_at),
    KEY idx_marketing_generation_run_brief (workspace_id, campaign_brief_id, updated_at),
    CONSTRAINT fk_marketing_generation_run_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS marketing_generation_artifacts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    workspace_id INT NOT NULL,
    generation_run_id BIGINT UNSIGNED NOT NULL,
    uuid CHAR(36) NOT NULL,
    artifact_type ENUM('channel_copy','visual_brief') NOT NULL DEFAULT 'channel_copy',
    channel VARCHAR(40) NOT NULL,
    content_type VARCHAR(40) NOT NULL,
    status ENUM('generated','accepted','rejected','failed') NOT NULL DEFAULT 'generated',
    title VARCHAR(255) NOT NULL,
    body MEDIUMTEXT NULL,
    creative_direction_json JSON NULL,
    quality_json JSON NULL,
    source_context_json JSON NULL,
    provider_json JSON NULL,
    accepted_content_item_id INT NULL,
    visual_request_id BIGINT UNSIGNED NULL,
    rejection_reason VARCHAR(500) NULL,
    ordinal SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    accepted_by INT NULL,
    accepted_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_marketing_generation_artifact_uuid (workspace_id, uuid),
    KEY idx_marketing_generation_artifact_run (generation_run_id, ordinal, id),
    KEY idx_marketing_generation_artifact_status (workspace_id, status, updated_at),
    KEY idx_marketing_generation_artifact_content (workspace_id, accepted_content_item_id),
    KEY idx_marketing_generation_artifact_visual (workspace_id, visual_request_id),
    CONSTRAINT fk_marketing_generation_artifact_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_marketing_generation_artifact_run FOREIGN KEY (generation_run_id) REFERENCES marketing_generation_runs(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
